(0, '0.client-channel.google.com', 1, 'Google - To access Google Drive and Google Docs editors this domain must be whitelisted - https://support.google.com/a/answer/2589954?hl=en - SlyEWL')
(0, '1drv.com', 1, 'Microsoft OneDrive - Used as a short link for OneDrive documents - SlyEWL')
(0, '2.android.pool.ntp.org', 1, 'Google Android - A big virtual cluster of timeservers providing reliable time; This domain is used in Android devices - SlyEWL')
(0, '2.tlu.dl.delivery.mp.microsoft.com', 1, 'Microsoft Store - SlyEWL')
(0, '4.tlu.dl.delivery.mp.microsoft.com', 1, 'Microsoft Store - SlyEWL')
(0, '4unal8ngvngjm07lj2q2umlc4.litix.io', 1, 'YouTube - Required to connect to Nvidia Shield TV using the YouTube Mobile App - SlyEWL')
(0, '79423.analytics.edgekey.net', 1, 'Microsoft - SlyEWL')
(0, 'aad.cs.dds.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'accounts.epicgames.com', 1, 'Epic Games Required to login to your account - SlyEWL')
(0, 'accounts.scdn.co', 1, 'Spotify - Required to log in to your account through a browser - SlyEWL')
(0, 'accounts.spotify.com', 1, 'Spotify - SlyEWL')
(0, 'activate.adobe.com', 1, 'Adobe - SlyEWL')
(0, 'activity.windows.com', 1, 'Microsoft - SlyEWL')
(0, 'adf.ly', 1, 'URL Shortener - SlyEWL')
(0, 'ae01.alicdn.com', 1, 'Misc - SlyEWL')
(0, 'ajax.aspnetcdn.com', 1, 'Crucial CDN server - SlyEWL')
(0, 'ajax.cloudflare.com', 1, 'Crucial CDN server - SlyEWL')
(0, 'ajax.googleapis.com', 1, 'Crucial CDN server - SlyEWL')
(0, 'ajax.loli.net', 1, 'Crucial CDN server - SlyEWL')
(0, 'ajax.loli.net.cdn.cloudflare.net', 1, 'Crucial CDN server - SlyEWL')
(0, 'ajax.microsoft.com', 1, 'Crucial CDN server - SlyEWL')
(0, 'ajax.proxy.ustclug.org', 1, 'Crucial CDN server - SlyEWL')
(0, 'akamai-webcdn.kgstatic.net', 1, 'Crucial CDN server - SlyEWL')
(0, 'akamai-webcdn.kgstatic.net.edgesuite.net', 1, 'Crucial CDN server - SlyEWL')
(0, 'akamaihd.net', 1, 'Akamai Technologies - A is a global content delivery network (CDN) - SlyEWL')
(0, 'akamaitechnologies.com', 1, 'Akamai Technologies  - A global content delivery network (CDN) - SlyEWL')
(0, 'akamaized.net', 1, 'Akamai Technologies - A global content delivery network (CDN) - SlyEWL')
(0, 'albert.apple.com', 1, 'Apple - SlyEWL')
(0, 'alluremedia.com', 1, 'Misc - SlyEWL')
(0, 'amazonaws.com', 1, 'Amazon - Web Services (AWS) is a subsidiary of Amazon providing on-demand cloud computing platforms and APIs; Used to serve files and other static resources which are hosted on Amazon AWS - SlyEWL')
(0, 'amd.cdn.turner.com', 1, 'Turner - SlyEWL')
(0, 'amzn.com', 1, 'Amazon - SlyEWL')
(0, 'amzn.to', 1, 'Amazon - SlyEWL')
(0, 'android.clients.google.com', 1, 'Google Android -  Rquired to use the Google Play App - SlyEWL')
(0, 'android.googleapis.com', 1, 'Google - SlyEWL')
(0, 'announcements.vizio.com', 1, 'Vizio - SlyEWL')
(0, 'api-2-0.spot.im', 1, 'Comments on ign.com - SlyEWL')
(0, 'api-global.netflix.com', 1, 'Netflix - SlyEWL')
(0, 'api-tv.spotify.com', 1, 'Spotify to work on the TV - SlyEWL')
(0, 'api.accuweather.com', 1, 'Weather - SlyEWL')
(0, 'api.directory.signal.org', 1, 'Signal - SlyEWL')
(0, 'api.euro.hismarttv.com', 1, 'HiSmartTV - SlyEWL')
(0, 'api.facebook.com', 1, 'Facebook - SlyEWL')
(0, 'api.flightproxy.teams.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'api.github.com', 1, 'GitHub - Links essential data - SlyEWL')
(0, 'api.ipify.org', 1, 'Used to get your public IP address programmatically. ipify is completely opensource - SlyEWL')
(0, 'api.pluto.tv', 1, 'Pluto.tv - SlyEWL')
(0, 'api.rlje.net', 1, 'Used to deliver contents on video straming apps on hulu etc - SlyEWL')
(0, 'api.termius.com', 1, 'Termius - Required to login to your account using the desktop app - SlyEWL')
(0, 'api.twitter.com', 1, 'Twitter - SlyEWL')
(0, 'api.us.hismarttv.com', 1, 'HiSmartTV - SlyEWL')
(0, 'api.vizio.com', 1, 'Vizio - SlyEWL')
(0, 'api2.branch.io', 1, 'Reddit to open the official app on iPhone - SlyEWL')
(0, 'apicache.vudu.com', 1, 'HBBTV - SlyEWL')
(0, 'app-api.ted.com', 1, 'TED - Used by ted.com streams - SlyEWL')
(0, 'app.emby', 1, 'Misc - SlyEWL')
(0, 'app.plex.tv', 1, 'Plex Media Server - SlyEWL')
(0, 'appboot.netflix.com', 1, 'Netflix - SlyEWL')
(0, 'appboy-images.com', 1, 'Misc - SlyEWL')
(0, 'appldnld.apple.com.edgesuite.net', 1, 'Apple - SlyEWL')
(0, 'appleglobal.102.112.2o7.net', 1, 'Apple iOS - Required to add someone to your account recovery list - SlyEWL')
(0, 'appleid.apple.com', 1, 'Apple - Used to sign in to your account - SlyEWL')
(0, 'applicast.ga.sony.net', 1, 'Sony - SlyEWL')
(0, 'apps.bdimg.com', 1, 'Crucial CDN server - SlyEWL')
(0, 'apps.bdimg.jomodns.com', 1, 'Crucial CDN server - SlyEWL')
(0, 'apps.skype.com', 1, 'Microsoft Skype - Used to make group calls, group chats etc - SlyEWL')
(0, 'appsbackup-pa.clients6.google.com', 1, 'Google - Used to backup device settings and app data - SlyEWL')
(0, 'appsbackup-pa.googleapis.com', 1, 'Google - Used to backup device settings and app data - SlyEWL')
(0, 'appspot-preview.l.google.com', 1, 'Google - Used to deliver system updates to Moto phones - SlyEWL')
(0, 'apresolve.spotify.com', 1, 'Spotify - SlyEWL')
(0, 'apt.sonarr.tv', 1, 'Plex Media Server - Sonarr is a PVR for Usenet and BitTorrent users. It can monitor multiple RSS feeds for new episodes of your favorite shows and will grab, sort and rename them. - SlyEWL')
(0, 'arc.msn.com', 1, 'Microsoft - SlyEWL')
(0, 'aspnetcdn.com', 1, 'Microsoft - Used to deliver files such as Windows updates and other services - SlyEWL')
(0, 'assets.adobedtm.com', 1, 'Adobe - SlyEWL')
(0, 'attestation.xboxlive.com', 1, 'Microsoft Xbox - Used for Xbox updates, game downloads, acheivements - SlyEWL')
(0, 'audio2.spotify.com', 1, 'Spotify - SlyEWL')
(0, 'audio4-fa.scdn.co', 1, 'Spotify - SlyEWL')
(0, 'audiocontentdownload.apple.com', 1, 'Apple - SlyEWL')
(0, 'auth.samsungosp.com', 1, 'Samsung TV - SlyEWL')
(0, 'auth.split.io', 1, 'Spotify - Required to login to Spotify through browsers - SlyEWL')
(0, 'authsvc.teams.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'avpro.global.yamaha.com', 1, 'Yamaha AV Receivers - Blocks system updates on rx-v685 so we whitelist - SlyEWL')
(0, 'aws.amazon.com', 1, 'Amazon - SlyEWL')
(0, 'ax.phobos.apple.com.edgesuite.net', 1, 'Apple - Used by Apple Photos - SlyEWL')
(0, 'axm-adm-enroll.apple.com', 1, 'Apple - SlyEWL')
(0, 'axm-adm-mdm.apple.com', 1, 'Apple - SlyEWL')
(0, 'axm-adm-scep.apple.com', 1, 'Apple - SlyEWL')
(0, 'axm-app.apple.com', 1, 'Apple - SlyEWL')
(0, 'b-api.facebook.com', 1, 'Facebook - SlyEWL')
(0, 'b-graph.facebook.com', 1, 'Facebook - SlyEWL')
(0, 'best.aliexpress.com', 1, 'Misc - SlyEWL')
(0, 'bigzipfiles.facebook.com', 1, 'Facebook - SlyEWL')
(0, 'bing.com', 1, 'Microsoft - SlyEWL')
(0, 'bit.ly', 1, 'URL Shortener - SlyEWL')
(0, 'bpapi.apple.com', 1, 'Apple - SlyEWL')
(0, 'brightcove.net', 1, 'Video delivery systems, popular in entertainment and news sites - SlyEWL')
(0, 'browser.events.data.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'browser.pipe.aria.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'bufferapp.com', 1, 'Misc - SlyEWL')
(0, 'bugmenot.com', 1, 'Misc - SlyEWL')
(0, 'c.s-microsoft.com', 1, 'Microsoft - Used to deliver fonts - SlyEWL')
(0, 'captive.apple.com', 1, 'Apple - SlyEWL')
(0, 'catalog-public-service-prod.ak.epicgames.com', 1, 'Epic Games - SlyEWL')
(0, 'cdn-mobile.api.pluto.tv', 1, 'Pluto.tv - SlyEWL')
(0, 'cdn.appdynamics.com', 1, 'TDAmeritrade - SlyEWL')
(0, 'cdn.bootcdn.net', 1, 'Crucial CDN server - SlyEWL')
(0, 'cdn.bootcdn.net.maoyundns.com', 1, 'Crucial CDN server - SlyEWL')
(0, 'cdn.bootcss.com', 1, 'Crucial CDN server - SlyEWL')
(0, 'cdn.bootcss.com.maoyundns.com', 1, 'Crucial CDN server - SlyEWL')
(0, 'cdn.cloudflare.net', 1, 'CloudFlare - Used to deliver static files - SlyEWL')
(0, 'cdn.datatables.net', 1, 'Crucial CDN server - SlyEWL')
(0, 'cdn.discordapp.com', 1, 'Discord - Required content delivery network domain - SlyEWL')
(0, 'cdn.embed.ly', 1, 'Crucial CDN server - SlyEWL')
(0, 'cdn.embed.ly.cdn.cloudflare.net', 1, 'Crucial CDN server - SlyEWL')
(0, 'cdn.embedly.com', 1, 'Embedly - Used to embed videos, images and rich media from 300+ providers with just the URL - SlyEWL')
(0, 'cdn.fbsbx.com', 1, 'Misc - SlyEWL')
(0, 'cdn.jsdelivr.net', 1, 'Crucial CDN server - SlyEWL')
(0, 'cdn.jsdelivr.net.cdn.cloudflare.net', 1, 'Crucial CDN server - SlyEWL')
(0, 'cdn.materialdesignicons.com', 1, 'Crucial CDN server - SlyEWL')
(0, 'cdn.mathjax.org', 1, 'Crucial CDN server - SlyEWL')
(0, 'cdn.optimizely.com', 1, 'Optimizely - A progressive delivery and experimentation software for other companies - SlyEWL')
(0, 'cdn.plyr.io', 1, 'Crucial CDN server - SlyEWL')
(0, 'cdn.ravenjs.com', 1, 'Crucial CDN server - SlyEWL')
(0, 'cdn.refersion.com', 1, 'Misc - SlyEWL')
(0, 'cdn.samsungcloudsolution.com', 1, 'Samsung TV - SlyEWL')
(0, 'cdn.signal.org', 1, 'Signal - SlyEWL')
(0, 'cdn.staticfile.org', 1, 'Crucial CDN server - SlyEWL')
(0, 'cdn.vidible.tv', 1, 'Video delivery systems, popular in entertainment and news sites - SlyEWL')
(0, 'cdn2.optimizely.com', 1, 'Optimizely - A progressive delivery and experimentation software for other companies - SlyEWL')
(0, 'cdn3.optimizely.com', 1, 'Optimizely - A progressive delivery and experimentation software for other companies - SlyEWL')
(0, 'cdnjs.cloudflare.com', 1, 'Cloudflare - Used to deliver static files over CloudFlare CDN - SlyEWL')
(0, 'cdnjs.cloudflare.com', 1, 'Crucial CDN server - SlyEWL')
(0, 'cdnjs.loli.net', 1, 'Crucial CDN server - SlyEWL')
(0, 'cdnjs.loli.net.cdn.cloudflare.net', 1, 'Crucial CDN server - SlyEWL')
(0, 'cds.d3x4y6v5.hwcdn.net', 1, 'Github - Required CDN for downloading packages - SlyEWL')
(0, 'cds.s5x3j6q5.hwcdn.net', 1, 'Crucial CDN server - SlyEWL')
(0, 'cds.s5x3j6q5.hwcdn.net', 1, 'Github - Required CDN for downloading packages - SlyEWL')
(0, 'cert.mgt.xboxlive.com', 1, 'Microsoft Xbox - Used for Xbox updates, game downloads, acheivements - SlyEWL')
(0, 'certs.apple.com', 1, 'Apple - SlyEWL')
(0, 'cf.iadsdk.apple.com', 1, 'Apple - SlyEWL')
(0, 'chat.signal.org', 1, 'Signal - SlyEWL')
(0, 'chatsvcagg.teams.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'check2.tsb.co.uk', 1, 'Misc - SlyEWL')
(0, 'chevrolet.com', 1, 'Misc - SlyEWL')
(0, 'chtbl.com', 1, 'Plex Media Server - SlyEWL')
(0, 'click.redditmail.com', 1, 'Reddit - Required to open links sent via e-mail - SlyEWL')
(0, 'client-rapi.recombee.us', 1, 'AdultTime - SlyEWL')
(0, 'client-s.gateway.messenger.live.com', 1, 'Microsoft - SlyEWL')
(0, 'client.wns.windows.com', 1, 'Microsoft Store - SlyEWL')
(0, 'clientconfig.passport.net', 1, 'Microsoft - Windows Store App - SlyEWL')
(0, 'clients.config.office.net', 1, 'Microsoft - SlyEWL')
(0, 'cloudsync-prod.s3.amazonaws.com', 1, 'Origin Games - Cloud Saves - SlyEWL')
(0, 'cluster95-elbwpeel-12if8kvnohvm9-1396764601.us-east-1.elb.amazonaws.com', 1, 'Gasbuddy App Website - SlyEWL')
(0, 'cms.souqcdn.com', 1, 'Misc - SlyEWL')
(0, 'code.bildstatic.de', 1, 'Misc - SlyEWL')
(0, 'code.createjs.com', 1, 'Crucial CDN server - SlyEWL')
(0, 'code.jquery.com', 1, 'Crucial CDN server - SlyEWL')
(0, 'codepush.teams.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'cognito-identity.us-east-1.amazonaws.com', 1, 'Amazon - SlyEWL')
(0, 'color.adobe.com', 1, 'Adobe - SlyEWL')
(0, 'config.fp.measure.office.com', 1, 'Microsoft - SlyEWL')
(0, 'config.teams.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'configuration.apple.com', 1, 'Apple - SlyEWL')
(0, 'connect.facebook.com', 1, 'Facebook - SlyEWL')
(0, 'connect.facebook.net', 1, 'Required to login to Instagram - SlyEWL')
(0, 'connect.ubisoft.com', 1, 'Required to buy items from the Ubisoft Desktop App - SlyEWL')
(0, 'connectivitycheck.android.com', 1, 'Google Android - Used by mobiles devices to check internet connectivity - SlyEWL')
(0, 'connectivitycheck.gstatic.com', 1, 'Google - Used by mobiles devices to check internet connectivity - SlyEWL')
(0, 'connecttv.pelmorex.com', 1, 'Philips TV - SlyEWL')
(0, 'contentproxy.signal.org', 1, 'Signal - SlyEWL')
(0, 'continuum.dds.microsoft.com', 1, 'Microsoft - Used by YourPhone app by Microsoft on Windows 10 for mirroring Android notifications - SlyEWL')
(0, 'cp801.prod.do.dsp.mp.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'cpms.spop10.ams.plex.bz', 1, 'Plex Media Server - SlyEWL')
(0, 'cpms35.spop10.ams.plex.bz', 1, 'Plex Media Server - SlyEWL')
(0, 'creative.ak.fbcdn.net', 1, 'Facebook - SlyEWL')
(0, 'crl.apple.com', 1, 'Apple - SlyEWL')
(0, 'crl.entrust.net', 1, 'Apple - SlyEWL')
(0, 'crl3.digicert.com', 1, 'Digicert - SlyEWL')
(0, 'crl4.digicert.com', 1, 'Digicert - SlyEWL')
(0, 'cse.google.com', 1, 'Google - Custom search. Often used as a search functionality inside a website. https://programmablesearchengine.google.com/about/ - SlyEWL')
(0, 'csp.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'cssubmissions.apple.com', 1, 'Apple - SlyEWL')
(0, 'ctldl.windowsupdate.com', 1, 'Microsoft - Required for getting the lastest Windows Updates - SlyEWL')
(0, 'cws.conviva.com', 1, 'Conviva - Offers online video optimization and online video analytics. But it is neccessary to whitelist in order to watch many online contents - SlyEWL')
(0, 'd1oxlq5h9kq8q5.cloudfront.net', 1, 'Cloudfront - SlyEWL')
(0, 'd2c8v52ll5s99u.cloudfront.net', 1, 'Amazon - Used to deliver media such as videos in entertainment and news sites - SlyEWL')
(0, 'd2gatte9o95jao.cloudfront.net', 1, 'Amazon - Used to deliver media such as videos in entertainment and news sites - SlyEWL')
(0, 'd3a3ewgd1iewwz.cloudfront.net', 1, 'AdultTime - A required CDN of the site to access image, videos, etc - SlyEWL')
(0, 'd3aqoihi2n8ty8.cloudfront.net', 1, 'Twitch.tv - Required to load the live streams you want to see - SlyEWL')
(0, 'd83eunklitikj.cloudfront.net', 1, 'Cloudfront - SlyEWL')
(0, 'daily-mix.scdn.co', 1, 'Spotify - SlyEWL')
(0, 'dailymix-images.scdn.co', 1, 'Spotify - SlyEWL')
(0, 'dashboard.plex.tv', 1, 'Plex Media Server - SlyEWL')
(0, 'dataplicity.com', 1, 'Raspberry-Pi - Remotely control your pi - SlyEWL')
(0, 'datarouter.ol.epicgames.com', 1, 'Epic Games - essential service to play online - SlyEWL')
(0, 'de.ioam.de', 1, 'Misc - SlyEWL')
(0, 'dealer.spotify.com', 1, 'Spotify - SlyEWL')
(0, 'def-vef.xboxlive.com', 1, 'Microsoft Xbox - Used for Xbox updates, game downloads, acheivements - SlyEWL')
(0, 'delivery.vidible.tv', 1, 'Video delivery systems, popular in entertainment and news sites - SlyEWL')
(0, 'det-ta-g7g.amazon.com', 1, 'Amazon - SlyEWL')
(0, 'dev.virtualearth.net', 1, 'Microsoft - Used by Bing Maps to get information about various places - SlyEWL')
(0, 'developer.n.shifen.com', 1, 'Crucial CDN server - SlyEWL')
(0, 'device-messaging-na.amazon.com', 1, 'Amazon - SlyEWL')
(0, 'deviceenrollment.apple.com', 1, 'Apple - SlyEWL')
(0, 'devicelistenerprod.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'deviceportal.nettvservices.com', 1, 'Philips TV - SlyEWL')
(0, 'deviceservices-external.apple.com', 1, 'Apple - SlyEWL')
(0, 'devimages-cdn.apple.com', 1, 'Apple - SlyEWL')
(0, 'diagassets.apple.com', 1, 'Apple - SlyEWL')
(0, 'diagnostics.redditmedia.com', 1, 'Reddit - SlyEWL')
(0, 'directvapplications.hb.omtrdc.net', 1, 'Microsoft - SlyEWL')
(0, 'directvnow.com', 1, 'Misc - SlyEWL')
(0, 'display.ugc.bazaarvoice.com', 1, 'To display Ratings &amp; Reviews or Questions &amp; Answers in online stores - SlyEWL')
(0, 'displaycatalog.mp.microsoft.com', 1, 'Microsoft - Used for Xbox updates, game downloads, acheivements - SlyEWL')
(0, 'dl.delivery.mp.microsoft.com', 1, 'Used to deliver updates to Microsoft products - SlyEWL')
(0, 'dl.dropbox.com', 1, 'Dropbox - Used to download files from Dropbox - SlyEWL')
(0, 'dl.dropboxusercontent.com', 1, 'Dropbox - Used to download files from Dropbox - SlyEWL')
(0, 'dl.google.com', 1, 'Google - SlyEWL')
(0, 'dns.msftncsi.com', 1, 'Microsoft - Used to check whether the internet connection is up or not in Windows systems. - SlyEWL')
(0, 'doh.dns.apple.com', 1, 'Apple - SlyEWL')
(0, 'download.developer.apple.com', 1, 'Apple - SlyEWL')
(0, 'download.scdn.co', 1, 'Spotify - SlyEWL')
(0, 'download.sonarr.tv', 1, 'Plex Media Server - Sonarr is a PVR for Usenet and BitTorrent users. - SlyEWL')
(0, 'downloads.boi9osyg1uwtyafn.com', 1, 'MSys2 - Required CDN for sourcing and build packages - SlyEWL')
(0, 'drift.com', 1, 'Drift - Live chat platform for websites to chat with the website owner - SlyEWL')
(0, 'driftt.com', 1, 'Drift - Live chat platform for websites to chat with the website owner - SlyEWL')
(0, 'drscdn.500px.org', 1, 'HBBTV - SlyEWL')
(0, 'dsms0mj1bbhn4.cloudfront.net', 1, 'Cloudfront - SlyEWL')
(0, 'dualstack.osff.map.fastly.net', 1, 'Crucial CDN server - SlyEWL')
(0, 'dynupdate.no-ip.com', 1, 'No-IP - Offers DNS services, email, network monitoring and SSL certificates - SlyEWL')
(0, 'ec-ns.sascdn.com', 1, 'Misc - SlyEWL')
(0, 'ecn.dev.virtualearth.net', 1, 'Microsoft - Used by Bing Maps to get information about various places - SlyEWL')
(0, 'ecs.office.com', 1, 'Microsoft - SlyEWL')
(0, 'edge-chat.messenger.com', 1, 'Facebook Messenger - SlyEWL')
(0, 'edge-mqtt.facebook.com', 1, 'Facebook - SlyEWL')
(0, 'edge.activity.windows.com', 1, 'Sync Microsoft Edge with other devices - SlyEWL')
(0, 'edge.api.brightcove.com', 1, 'Video delivery systems, popular in entertainment and news sites - SlyEWL')
(0, 'edge.gycpi.b.yahoodns.net', 1, 'Yahoo - If not whitelisted it breaks the entire website - SlyEWL')
(0, 'edge.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'eds.xboxlive.com', 1, 'Microsoft Xbox - Used for Xbox updates, game downloads, acheivements - SlyEWL')
(0, 'embed.spotify.com', 1, 'Spotify - SlyEWL')
(0, 'emea.ng.msg.teams.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'emea.pptservicescast.officeapps.live.com', 1, 'Microsoft - SlyEWL')
(0, 'encore.scdn.co', 1, 'Spotify - Required to log in to your account through a browser - SlyEWL')
(0, 'entitlement-public-service-prod.ak.epicgames.com', 1, 'Epic Games - SlyEWL')
(0, 'entitlement.auth.adobe.com', 1, 'Adobe - SlyEWL')
(0, 'eos-gateway-ingressv2-prod-c2-w4.befa.live.use1a.on.epicgames.com', 1, 'Epic Games - Loads essential game traffic for online play - SlyEWL')
(0, 'epg.corio.com', 1, 'Philips TV - SlyEWL')
(0, 'et.topazlabs.com', 1, 'Topaz Labs - Required to download algorithms - SlyEWL')
(0, 'europe.cp.wd.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'europe.smartscreen-prod.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'europe.smartscreen.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'events-test-v2.redditmedia.com', 1, 'Reddit - SlyEWL')
(0, 'events-test.redditmedia.com', 1, 'Reddit - SlyEWL')
(0, 'events.gfe.nvidia.com', 1, 'Nvidia - SlyEWL')
(0, 'events.redditmedia.com', 1, 'Reddit - SlyEWL')
(0, 'facebook.com', 1, 'Facebook - SlyEWL')
(0, 'facebook.net', 1, 'Facebook - SlyEWL')
(0, 'fb.me', 1, 'Facebook - SlyEWL')
(0, 'fba.apple.com', 1, 'Apple - SlyEWL')
(0, 'fbcdn-creative-a.akamaihd.net', 1, 'Akami - SlyEWL')
(0, 'fbcdn.net', 1, 'Facebook - SlyEWL')
(0, 'fe3.delivery.dsp.mp.microsoft.com.nsatc.net', 1, 'Microsoft - SlyEWL')
(0, 'fe3cr.delivery.mp.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'filament.io', 1, 'Misc - SlyEWL')
(0, 'firestore.googleapis.com', 1, 'Google - SlyEWL')
(0, 'fivethirtyeight.com', 1, 'Misc - SlyEWL')
(0, 'fonts.gstatic.com', 1, 'Google - Used to deliver Google Fonts - SlyEWL')
(0, 'fonts.loli.net', 1, 'Crucial CDN server - SlyEWL')
(0, 'fonts.loli.net.cdn.cloudflare.net', 1, 'Crucial CDN server - SlyEWL')
(0, 'forms.office.com', 1, 'Microsoft - SlyEWL')
(0, 'forums.sonarr.tv', 1, 'Plex Media Server - Sonarr is a PVR for Usenet and BitTorrent users. - SlyEWL')
(0, 'fpdownload.adobe.com', 1, 'Adobe - SlyEWL')
(0, 'fs.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'g.live.com', 1, 'Microsoft - Outlook.com and OneDrive products. Backup bitlocker recovery key to Microsoft account - SlyEWL')
(0, 'gateway.cname.ustclug.org', 1, 'Crucial CDN server - SlyEWL')
(0, 'gdlp01.c-wss.com', 1, 'Misc - SlyEWL')
(0, 'gdmf.apple.com', 1, 'Apple - SlyEWL')
(0, 'geo-prod.do.dsp.mp.microsoft.com', 1, 'Microsoft - Enables connections to Windows Update - SlyEWL')
(0, 'geo.opera.com', 1, 'HBBTV - SlyEWL')
(0, 'geo3.ggpht.com', 1, 'Google - Used to deliver static files over the internet - SlyEWL')
(0, 'geolocation.onetrust.com', 1, 'Nvidia Shield TV - SlyEWL')
(0, 'geover.prod.do.dsp.mp.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'gfwsl.geforce.com', 1, 'Nvidia Geforce - Used for checking nVidia driver updates - SlyEWL')
(0, 'gg.apple.com', 1, 'Apple - SlyEWL')
(0, 'giphy-proxy-production.whispersystems.org', 1, 'Misc - SlyEWL')
(0, 'giphy.com', 1, 'Giphy - Gifs hosting platform - SlyEWL')
(0, 'gitcdn.github.io', 1, 'Crucial CDN server - SlyEWL')
(0, 'github.com', 1, 'GitHub - provides hosting for software development and version control using Git - SlyEWL')
(0, 'github.io', 1, 'GitHub - Used for GitHub pages - SlyEWL')
(0, 'global-dealer-ssl.spotify.com', 1, 'Spotify - SlyEWL')
(0, 'gnf-mdn.apple.com', 1, 'Apple - SlyEWL')
(0, 'gnf-mr.apple.com', 1, 'Apple - SlyEWL')
(0, 'go.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'go.trouter.teams.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'goo.gl', 1, 'Google - SlyEWL')
(0, 'googleapis.com', 1, 'Google - An important domain used to provide APIs to various Google services - SlyEWL')
(0, 'googleapis.l.google.com', 1, 'Google - SlyEWL')
(0, 'googlehosted.l.googleusercontent.com', 1, 'Google - SlyEWL')
(0, 'graph.facebook.com', 1, 'Facebook - SlyEWL')
(0, 'graph.instagram.com', 1, 'Facebook - SlyEWL')
(0, 'graph.oculus.com', 1, 'Facebook - SlyEWL')
(0, 'graphql.epicgames.com', 1, 'Epic Games - Required for the store to work properly - SlyEWL')
(0, 'gravatar.com', 1, 'Gravatar is a service for providing globally unique avatars - SlyEWL')
(0, 'gs.apple.com', 1, 'Apple - SlyEWL')
(0, 'gsa.apple.com', 1, 'Apple - SlyEWL')
(0, 'gsp-ssl.ls-apple.com.akadns.net', 1, 'Apple - SlyEWL')
(0, 'gsp-ssl.ls.apple.com', 1, 'Apple - SlyEWL')
(0, 'gsp1.apple.com', 1, 'Apple - SlyEWL')
(0, 'gstatic.com', 1, 'Google - gstatic.com is a cookieless domain to deliver static content for Google - SlyEWL')
(0, 'gstaticadssl.l.google.com', 1, 'Crucial CDN server - SlyEWL')
(0, 'gstaticadssl.l.google.com', 1, 'Google - SlyEWL')
(0, 'gucl-6.ap.spotify.com', 1, 'Spotify - SlyEWL')
(0, 'h-microsoft.online-metrix.net', 1, 'Microsoft - Required to download Windows 11 ISO file from the official MS website - SlyEWL')
(0, 'h-sdk.online-metrix.net', 1, 'Misc - SlyEWL')
(0, 'has.spserv.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'heartbeat.dm.origin.com', 1, 'Misc - SlyEWL')
(0, 'help.ui.xboxlive.com', 1, 'Microsoft Xbox - Used for Xbox updates, game downloads, acheivements - SlyEWL')
(0, 'hls.ted.com', 1, 'Used by ted.com streams - SlyEWL')
(0, 'hosts-file.net', 1, 'Misc - SlyEWL')
(0, 'hostsfile.mine.nu', 1, 'Misc - SlyEWL')
(0, 'hostsfile.org', 1, 'Misc - SlyEWL')
(0, 'humb.apple.com', 1, 'Apple - SlyEWL')
(0, 'i.cdn.turner.com', 1, 'Turner - SlyEWL')
(0, 'i.reddit.com', 1, 'Reddit - SlyEWL')
(0, 'i.s-microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'i.scdn.co', 1, 'Spotify - SlyEWL')
(0, 'i.ytimg.com', 1, 'Google - Used to deliver thumbails in YouTube - SlyEWL')
(0, 'i1.ytimg.com', 1, 'Google - Used to deliver thumbails in YouTube - SlyEWL')
(0, 'iadsdk.apple.com', 1, 'Apple - SlyEWL')
(0, 'ic3.events.data.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'icloud.com', 1, 'Apple - SlyEWL')
(0, 'identity.apple.com', 1, 'Apple - SlyEWL')
(0, 'idmsa.apple.com', 1, 'Apple - SlyEWL')
(0, 'iduwdjf.qiniudns.com', 1, 'Crucial CDN server - SlyEWL')
(0, 'ig.apple.com', 1, 'Apple - SlyEWL')
(0, 'images.ctfassets.net', 1, 'AdultTime.com - Icons - SlyEWL')
(0, 'images.pluto.tv', 1, 'Pluto.tv - SlyEWL')
(0, 'images.vizio.com', 1, 'Vizio - SlyEWL')
(0, 'imagesak.secureserver.net', 1, 'GoDaddy - Webmail buttons - SlyEWL')
(0, 'imasdk.googleapis.com', 1, 'Google - SlyEWL')
(0, 'img.vidible.tv', 1, 'Video delivery systems, popular in entertainment and news sites - SlyEWL')
(0, 'imgix.net', 1, 'Misc - SlyEWL')
(0, 'imgs.xkcd.com', 1, 'XKCD - Used to deliver images - SlyEWL')
(0, 'infolink.pavv.co.kr', 1, 'Philips TV - SlyEWL')
(0, 'instagram.c10r.facebook.com', 1, 'Facebook - SlyEWL')
(0, 'instantmessaging-pa.googleapis.com', 1, 'Google - An important domain used to provide APIs to various Google services - SlyEWL')
(0, 'intercom.io', 1, 'Live chat platform for websites to chat with the website owner. Blocking this domain will block chat widget - SlyEWL')
(0, 'ip-api.com', 1, 'Microsoft - Updates virus definitions if unknown suspicious files are detected. This will reach out to the server for more information. - SlyEWL')
(0, 'iprofiles.apple.com', 1, 'Apple - SlyEWL')
(0, 'ipv6.msftncsi.com', 1, 'Microsoft - SlyEWL')
(0, 'isu.apple.com', 1, 'Apple - SlyEWL')
(0, 'itunes-apple.com.akadns.net', 1, 'Apple - SlyEWL')
(0, 'itunes.apple.com.edgesuite.net', 1, 'Apple - SlyEWL')
(0, 'itunes.com', 1, 'Apple - SlyEWL')
(0, 'itv.ard.de', 1, 'HBBTV - SlyEWL')
(0, 'j.mp', 1, 'Misc - SlyEWL')
(0, 'jlduihq7lrcdxgw4vrndhdfcsq.appsync-api.us-east-1.amazonaws.com', 1, 'AdultTime - A required CDN of the site to access image, videos, etc - SlyEWL')
(0, 'jquery.com', 1, 'jQuery is a JavaScript library. Also used to deliver the files over CDN - SlyEWL')
(0, 'js.appboycdn.com', 1, 'Crucial CDN server - SlyEWL')
(0, 'js.maxmind.com', 1, 'Microsoft - SlyEWL')
(0, 'js.stripe.com', 1, 'Indiegogo - SlyEWL')
(0, 'jsdelivr.net', 1, 'jsDelivr is a free public CDN for open-source projects. It can serve web files directly from the npm registry and GitHub repositories without any configuration - SlyEWL')
(0, 'json.bild.de', 1, 'Misc - SlyEWL')
(0, 'keyserver.ubuntu.com', 1, 'Github - Required CDN for downloading packages - SlyEWL')
(0, 'keystone.mwbsys.com', 1, 'Malwarebytes - Verifies Malwarebytes software license - SlyEWL')
(0, 'l.facebook.com', 1, 'Facebook - SlyEWL')
(0, 'l.messenger.com', 1, 'Microsoft - SlyEWL')
(0, 'lastfm-img2.akamaized.net', 1, 'Used by last.fm to deliver images - SlyEWL')
(0, 'lb.sae.sina.com.cn', 1, 'Crucial CDN server - SlyEWL')
(0, 'lcdn-locator.apple.com', 1, 'Apple - SlyEWL')
(0, 'lcdn-registration.apple.com', 1, 'Apple - SlyEWL')
(0, 'lcprd1.samsungcloudsolution.net', 1, 'Samsung TV - SlyEWL')
(0, 'lib.baomitu.com', 1, 'Crucial CDN server - SlyEWL')
(0, 'lib.baomitu.com.qh-cdn.com', 1, 'Crucial CDN server - SlyEWL')
(0, 'lib.sinaapp.com', 1, 'Crucial CDN server - SlyEWL')
(0, 'libs.baidu.com', 1, 'Crucial CDN server - SlyEWL')
(0, 'licensing.mp.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'licensing.xboxlive.com', 1, 'Microsoft Xbox - Used for Xbox updates, game downloads, acheivements - SlyEWL')
(0, 'lineup-images.scdn.co', 1, 'Spotify - SlyEWL')
(0, 'linkedin.com', 1, 'Misc - SlyEWL')
(0, 'links.shoppers.instacartemail.com', 1, 'Instacart - Required to unsubscribe from their email lists - SlyEWL')
(0, 'linuxtracker.org', 1, 'Linux - SlyEWL')
(0, 'live.com', 1, 'Microsoft - It is a personal information manager web app from Microsoft consisting of webmail, calendaring, contacts, and tasks services - SlyEWL')
(0, 'livepassdl.conviva.com', 1, 'Conviva - offers online video optimization and online video analytics. Neccessary to whitelist in order to watch many online contents - SlyEWL')
(0, 'lm.licenses.adobe.com', 1, 'Adobe - SlyEWL')
(0, 'location-api.hdhomerun.com', 1, 'SiliconDust HDHomeRun - Required for firmware updates - SlyEWL')
(0, 'login.aliexpress.com', 1, 'Misc - SlyEWL')
(0, 'login.live.com', 1, 'Microsoft - The following endpoint is used to authenticate a device. - SlyEWL')
(0, 'login.microsoftonline.com', 1, 'Microsoft - Office apps - SlyEWL')
(0, 'login5.spotify.com', 1, 'Spotify - SlyEWL')
(0, 'logincdn.msauth.net', 1, 'Microsoft Windows - Required to sign in to your account during a fresh installation - SlyEWL')
(0, 'logs.juspay.in', 1, 'Misc - SlyEWL')
(0, 'lzzos7clo5.execute-api.us-east-1.amazonaws.com', 1, 'AdultTime - A required CDN of the site to access image, videos, etc - SlyEWL')
(0, 'm.facebook.com', 1, 'Facebook Mobile - SlyEWL')
(0, 'm.hotmail.com', 1, 'Microsoft - SlyEWL')
(0, 'm.reddit.com', 1, 'Reddit - Required to access on mobile devices - SlyEWL')
(0, 'm.weeklyad.target.com', 1, 'Target - SlyEWL')
(0, 'm.youtube.com', 1, 'YouTube - SlyEWL')
(0, 'm3u8.gammacdn.com', 1, 'AdultTime - Required for streaming - SlyEWL')
(0, 'mamservice.manage.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'manifest.googlevideo.com', 1, 'Google - SlyEWL')
(0, 'market.spotify.com', 1, 'Spotify - SlyEWL')
(0, 'martellmalone.com', 1, 'Github - Required CDN for downloading packages - SlyEWL')
(0, 'mask-api.icloud.com', 1, 'Apple - SlyEWL')
(0, 'mask-h2.icloud.com', 1, 'Apple - SlyEWL')
(0, 'mask.icloud.com', 1, 'Apple - SlyEWL')
(0, 'mat1.gtimg.com', 1, 'Crucial CDN server - SlyEWL')
(0, 'mat1.gtimg.com.tegsea.tc.qq.com', 1, 'Crucial CDN server - SlyEWL')
(0, 'materialdesignicons.b-cdn.net', 1, 'Crucial CDN server - SlyEWL')
(0, 'mathjax.rstudio.com', 1, 'Crucial CDN server - SlyEWL')
(0, 'maxcdn.bootstrapcdn.com', 1, 'Crucial CDN server - SlyEWL')
(0, 'mdmenrollment.apple.com', 1, 'Apple - SlyEWL')
(0, 'medium.com', 1, 'Misc - SlyEWL')
(0, 'mesu.apple.com', 1, 'Apple - SlyEWL')
(0, 'meta-db-worker02.pop.ric.plex.bz', 1, 'Plex Media Server - SlyEWL')
(0, 'meta.plex.bz', 1, 'Plex Media Server - SlyEWL')
(0, 'meta.plex.tv', 1, 'Plex Media Server - SlyEWL')
(0, 'metrics.icloud.com', 1, 'Apple - SlyEWL')
(0, 'metrics.plex.tv', 1, 'Plex Media Server - SlyEWL')
(0, 'metrics.ubuntu.com', 1, 'Ubuntu Jammy Telemetry - SlyEWL')
(0, 'microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'microsoftonline.com', 1, 'Microsoft - Checked by the operating systems when connecting via wifi - SlyEWL')
(0, 'mirror.clarkson.edu', 1, 'Github - Required CDN for downloading packages - SlyEWL')
(0, 'mirror.msys2.org', 1, 'Github - Required CDN for downloading packages - SlyEWL')
(0, 'mirror.umd.edu', 1, 'Github - Required CDN for downloading packages - SlyEWL')
(0, 'mirror2.sandyriver.net', 1, 'Github - Required CDN for downloading packages - SlyEWL')
(0, 'mobile-ap.spotify.com', 1, 'Spotify - SlyEWL')
(0, 'mobile.pipe.aria.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'mobile.twitter.com', 1, 'Twitter - SlyEWL')
(0, 'mobileandroidapi.punchh.com', 1, 'Misc - SlyEWL')
(0, 'models.topazlabs.com', 1, 'Topaz Labs - Required to download algorithms - SlyEWL')
(0, 'mqtt-mini.facebook.com', 1, 'Facebook - SlyEWL')
(0, 'mqtt.c10r.facebook.com', 1, 'Facebook - SlyEWL')
(0, 'mrs-efz.ms-acdc.office.com', 1, 'Microsoft - SlyEWL')
(0, 'mscomajax.vo.msecnd.net', 1, 'Crucial CDN server - SlyEWL')
(0, 'msedge.api.cdp.microsoft.com', 1, 'Download Edge Browser Updates - SlyEWL')
(0, 'msftncsi.com', 1, 'Microsoft - Checked by the operating systems when connecting via wifi - SlyEWL')
(0, 'my.plexapp.com', 1, 'Plex Media Server - SlyEWL')
(0, 'netdna.bootstrapcdn.com', 1, 'Crucial CDN server - SlyEWL')
(0, 'netflix.com', 1, 'Netflix - SlyEWL')
(0, 'newjams-images.scdn.co', 1, 'Spotify - SlyEWL')
(0, 'news.iadsdk.apple.com', 1, 'Apple - SlyEWL')
(0, 'nexus.ensighten.com', 1, 'Microsoft - SlyEWL')
(0, 'nexusrules.officeapps.live.com', 1, 'Microsoft - Office apps - SlyEWL')
(0, 'ngfts.lge.com', 1, 'LG TV - SlyEWL')
(0, 'nine.plugins.plexapp.com', 1, 'Plex Media Server - SlyEWL')
(0, 'nleditor.osi.office.net', 1, 'Microsoft - SlyEWL')
(0, 'no-ip.com', 1, 'No-IP offers DNS services, email, network monitoring and SSL certificates - SlyEWL')
(0, 'node.plexapp.com', 1, 'Plex Media Server - SlyEWL')
(0, 'northeurope-prod-4.notifications.teams.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'notify.xboxlive.com', 1, 'Microsoft Xbox - Used for Xbox updates, game downloads, acheivements - SlyEWL')
(0, 'npr-news.streaming.adswizz.com', 1, 'Used for NPR morning news and podcasts - SlyEWL')
(0, 'nrdp.nccp.netflix.com', 1, 'Netflix - SlyEWL')
(0, 'nrdp.prod.cloud.netflix.com', 1, 'Netflix - Needed to login on Nvidia Shield TV - SlyEWL')
(0, 'ns.itunes.apple.com', 1, 'Apple - SlyEWL')
(0, 'ns1.dropbox.com', 1, 'Dropbox - Used to download files from Dropbox - SlyEWL')
(0, 'ns11.whois.co.kr', 1, 'Philips TV - SlyEWL')
(0, 'ns2.dropbox.com', 1, 'Dropbox - Used to download files from Dropbox - SlyEWL')
(0, 'o1.email.plex.tv', 1, 'Plex Media Server - SlyEWL')
(0, 'o2.sg0.plex.tv', 1, 'Plex Media Server - SlyEWL')
(0, 'oauthaccountmanager.googleapis.com', 1, 'Google - SlyEWL')
(0, 'objects.githubusercontent.com', 1, 'Github - Required CDN for downloading packages - SlyEWL')
(0, 'ocsp.apple.com', 1, 'Apple - iOS developers are able to distribute apps outside of the App Store using an Enterprise provisioning profile. Apple can revoke these kinds of apps by using this domain - SlyEWL')
(0, 'ocsp.digicert.com', 1, 'Digicert - SSL Verification - SlyEWL')
(0, 'ocsp.entrust.net', 1, 'Apple - SlyEWL')
(0, 'ocsp.verisign.net', 1, 'Misc - SlyEWL')
(0, 'ocsp2.apple.com', 1, 'Apple - SlyEWL')
(0, 'office.com', 1, 'Microsoft - Office apps - SlyEWL')
(0, 'office.net', 1, 'Microsoft - Office apps - SlyEWL')
(0, 'office365.com', 1, 'Microsoft - Office apps - SlyEWL')
(0, 'officecdnmac.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'officeci-mauservice.azurewebsites.net', 1, 'Microsoft - SlyEWL')
(0, 'officeclient.microsoft.com', 1, 'Microsoft - Office apps - SlyEWL')
(0, 'om.cbsi.com', 1, 'CBS - All Access on streaming platforms - SlyEWL')
(0, 'onedrive.live.com', 1, 'Microsoft - Used to sign in to One Drive - SlyEWL')
(0, 'oops.redditmedia.com', 1, 'Reddit - SlyEWL')
(0, 'open.spotify.com', 1, 'Spotify - SlyEWL')
(0, 'openpgpkey.gmail.com', 1, 'Github - Required CDN for downloading packages - SlyEWL')
(0, 'openpgpkey.martellmalone.com', 1, 'Github - Required CDN for downloading packages - SlyEWL')
(0, 'osb-ussvc.samsungqbe.com', 1, 'Samsung TV - SlyEWL')
(0, 'oscdn.apple.com', 1, 'Apple - SlyEWL')
(0, 'oscp.apple.com', 1, 'Apple - SlyEWL')
(0, 'osrecovery.apple.com', 1, 'Apple - SlyEWL')
(0, 'ota-downloads.nvidia.com', 1, 'Nvidia - SlyEWL')
(0, 'otn.samsungcloudcdn.com', 1, 'Samsung TV - SlyEWL')
(0, 'otnprd10.samsungcloudsolution.net', 1, 'Samsung TV - SlyEWL')
(0, 'otnprd11.samsungcloudsolution.net', 1, 'Samsung TV - SlyEWL')
(0, 'otnprd8.samsungcloudsolution.net', 1, 'Samsung TV - SlyEWL')
(0, 'otnprd9.samsungcloudsolution.net', 1, 'Samsung TV - SlyEWL')
(0, 'outlook-1.cdn.office.net', 1, 'Microsoft - SlyEWL')
(0, 'outlook.ha.office365.com', 1, 'Microsoft - SlyEWL')
(0, 'outlook.live.com', 1, 'Microsoft - Used for Outlook email - SlyEWL')
(0, 'outlook.office.com', 1, 'Microsoft - SlyEWL')
(0, 'outlook.office365.com', 1, 'Microsoft - Used for Outlook email.ent - SlyEWL')
(0, 'p11.techlab-cdn.com', 1, 'Misc - SlyEWL')
(0, 'pagecdn.io', 1, 'Crucial CDN server - SlyEWL')
(0, 'pgl.yoyo.org', 1, 'Misc - SlyEWL')
(0, 'pings.conviva.com', 1, 'Conviva - offers online video optimization and online video analytics. But it is neccessary to whitelist in order to watch many online contents - SlyEWL')
(0, 'pinterest.com', 1, 'Misc - SlyEWL')
(0, 'placehold.it', 1, 'Placehold.it, Image placeholders often used during web page loading - SlyEWL')
(0, 'placeholdit.imgix.net', 1, 'Placehold.it, Image placeholders often used during web page loading - SlyEWL')
(0, 'platform.cid.samba.tv', 1, 'Sony Bravia TV - SlyEWL')
(0, 'play.kayosports.com.au', 1, 'Kayo is an Australian sports streaming service created for sports-loving Aussies - SlyEWL')
(0, 'play.spotify.com', 1, 'Spotify - SlyEWL')
(0, 'play.spotify.edgekey.net', 1, 'Spotify - SlyEWL')
(0, 'players.brightcove.net', 1, 'Video delivery systems, popular in entertainment and news sites - SlyEWL')
(0, 'players.pluto.tv', 1, 'Pluto.tv - SlyEWL')
(0, 'playgrounds-assets-cdn.apple.com', 1, 'Apple - SlyEWL')
(0, 'playgrounds-cdn.apple.com', 1, 'Apple - SlyEWL')
(0, 'plex.tv', 1, 'Plex Media Server - SlyEWL')
(0, 'pmd.cdn.turner.com', 1, 'Turner - SlyEWL')
(0, 'portal.fb.com', 1, 'Facebook - SlyEWL')
(0, 'portal.store.sonyentertainmentnetwork.com', 1, 'Sony - SlyEWL')
(0, 'ppq.apple.com', 1, 'Apple - SlyEWL')
(0, 'presence.teams.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'pricelist.skype.com', 1, 'Microsoft Skype - Used to make group calls, group chats etc. on Skype - SlyEWL')
(0, 'privacyportal-de.onetrust.com', 1, 'Nvidia Shield TV - SlyEWL')
(0, 'prod.telemetry.ros.rockstargames.com', 1, 'Rockstar Games - SlyEWL')
(0, 'products.office.com', 1, 'Microsoft Office - Microsoft - Office apps - SlyEWL')
(0, 'proxy.plex.bz', 1, 'Plex Media Server - SlyEWL')
(0, 'proxy.plex.tv', 1, 'Plex Media Server - SlyEWL')
(0, 'proxy02.pop.ord.plex.bz', 1, 'Plex Media Server - SlyEWL')
(0, 'pubsub.plex.bz', 1, 'Plex Media Server - SlyEWL')
(0, 'pubsub.plex.tv', 1, 'Plex Media Server - SlyEWL')
(0, 'r.manage.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'radarsubmissions.apple.com', 1, 'Apple - SlyEWL')
(0, 'raw.githubusercontent.com', 1, 'GitHub - It is used to serve unprocessed versions of files stored in GitHub repositories. - SlyEWL')
(0, 'redd.it', 1, 'Reddit - SlyEWL')
(0, 'reddit-uploaded-media.s3-accelerate.amazonaws.com', 1, 'Amazon - SlyEWL')
(0, 'reddit.com', 1, 'Reddit - SlyEWL')
(0, 'reddit.map.fastly.net', 1, 'Reddit - SlyEWL')
(0, 'redditmedia.com', 1, 'Reddit - SlyEWL')
(0, 'redirector.googlevideo.com', 1, 'Google - SlyEWL')
(0, 'redirector.gvt1.com', 1, 'Android TV Updates - SlyEWL')
(0, 'refersion.com', 1, 'Misc - SlyEWL')
(0, 'reminders-pa.googleapis.com', 1, 'Google - SlyEWL')
(0, 'res-1.cdn.office.net', 1, 'Microsoft - SlyEWL')
(0, 'res.cloudinary.com', 1, 'Cloudinary - Provides a cloud-based image and video management services - SlyEWL')
(0, 'rest.iad-03.braze.com', 1, 'Misc - SlyEWL')
(0, 'rover.ebay.com', 1, 'Ebay - SlyEWL')
(0, 'rupload.facebook.com', 1, 'Facebook - SlyEWL')
(0, 's.cdn.turner.com', 1, 'Turner - SlyEWL')
(0, 's.gateway.messenger.live.com', 1, 'Microsoft - Personal information manager web app from Microsoft consisting of webmail, calendaring, contacts, and tasks services - SlyEWL')
(0, 's.marketwatch.com', 1, 'MarketWatch - Loadeds images on marketwatch.com - SlyEWL')
(0, 's.mzstatic.com', 1, 'Misc - SlyEWL')
(0, 's.shopify.com', 1, 'Blocked by a lot of lists - SlyEWL')
(0, 's.yimg.com', 1, 'Yahoo - SlyEWL')
(0, 's.youtube.com', 1, 'Google YouTube - Used to record YouTube watch history. Blocking this domain will pause your watch history on YouTube - SlyEWL')
(0, 's.ytimg.com', 1, 'Google - Used to deliver thumbails in YouTube - SlyEWL')
(0, 's.zkcdn.net', 1, 'Misc - SlyEWL')
(0, 's1.wp.com', 1, 'WordPress - Used to feliver static files and media for websites which are hosted on wordpress.com platform - SlyEWL')
(0, 's1.yimg.com', 1, 'Yahoo - SlyEWL')
(0, 's2.youtube.com', 1, 'Google YouTube - Used to record YouTube watch history. Blocking this domain will pause your watch history on YouTube - SlyEWL')
(0, 's3-eu-central-1.amazonaws.com', 1, 'Discord - MEE6 Bot - SlyEWL')
(0, 's3-eu-west-1.amazonaws.com', 1, 'Amazon - SlyEWL')
(0, 's3.amazonaws.com', 1, 'Amazon - Used to deliver files that are stored in Amazon AWS S3 storage buckets - SlyEWL')
(0, 'sa.symcb.com', 1, 'Symantec - Certificate Revocation List servers; Used by a number of companies including Microsoft - SlyEWL')
(0, 'samsungosp.com', 1, 'Samsung TV - SlyEWL')
(0, 'samsungotn.net', 1, 'Samsung TV - SlyEWL')
(0, 'scontent-atl3-1.xx.fbcdn.net', 1, 'Facebook - Messenger - SlyEWL')
(0, 'scontent-lhr3-1.xx.fbcdn.net', 1, 'Facebook - Messenger - SlyEWL')
(0, 'scontent-mia3-1.xx.fbcdn.net', 1, 'Facebook - Messenger - SlyEWL')
(0, 'scontent-ort2-1.xx.fbcdn.net', 1, 'Facebook - Messenger - SlyEWL')
(0, 'scontent.fgdl5-1.fna.fbcdn.net', 1, 'Facebook - Messenger - SlyEWL')
(0, 'scontent.xx.fbcdn.net', 1, 'Facebook - SlyEWL')
(0, 'script.ioam.de', 1, 'Misc - SlyEWL')
(0, 'sdk.split.io', 1, 'Termius - Required to login to your account using the desktop app - SlyEWL')
(0, 'sdn.geekzu.org', 1, 'Crucial CDN server - SlyEWL')
(0, 'sdn.inbond.gslb.geekzu.org', 1, 'Crucial CDN server - SlyEWL')
(0, 'secure.avangate.com', 1, 'Used to perform online payments - SlyEWL')
(0, 'secure.brightcove.com', 1, 'Video delivery systems, popular in entertainment and news sites - SlyEWL')
(0, 'secure.netflix.com', 1, 'Netflix - SlyEWL')
(0, 'secure.surveymonkey.com', 1, 'Used by Survey Monkey to deliver surveys - SlyEWL')
(0, 'seedbox-react-infra.s3.amazonaws.com', 1, 'AdultTime - Required to display similar actors - SlyEWL')
(0, 'self.events.data.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'sendbirdproxyk8s.chat.redditmedia.com', 1, 'Reddit - SlyEWL')
(0, 'serverstatus.apple.com', 1, 'Apple - SlyEWL')
(0, 'services.sonarr.tv', 1, 'Plex Media Server - Sonarr is a PVR for Usenet and BitTorrent users. - SlyEWL')
(0, 'settings-win.data.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'setup.icloud.com', 1, 'Apple - SlyEWL')
(0, 'shareaholic.com', 1, 'Misc - SlyEWL')
(0, 'sharepoint.com', 1, 'Misc - SlyEWL')
(0, 'signal.org', 1, 'Signal - SlyEWL')
(0, 'silo.pluto.tv', 1, 'Pluto.tv - SlyEWL')
(0, 'siloh.pluto.tv', 1, 'Pluto.tv - SlyEWL')
(0, 'skl.apple.com', 1, 'Apple - SlyEWL')
(0, 'skyhook.sonarr.tv', 1, 'Plex Media Server - Sonarr is a PVR for Usenet and BitTorrent users. - SlyEWL')
(0, 'skype.com', 1, 'Microsoft - SlyEWL')
(0, 'sls.update.microsoft.com.akadns.net', 1, 'Microsoft - SlyEWL')
(0, 'society6.com', 1, 'Misc - SlyEWL')
(0, 'someonewhocares.org', 1, 'Misc - SlyEWL')
(0, 'souqcdn.com', 1, 'Misc - SlyEWL')
(0, 'spclient-wg.spotify.com', 1, 'Spotify - SlyEWL')
(0, 'spclient.wg.spotify.com', 1, 'Spotify - SlyEWL')
(0, 'sq-device.apple.com', 1, 'Apple - SlyEWL')
(0, 'ssl.google-analytics.com', 1, 'Google - SlyEWL')
(0, 'ssl.p.jwpcdn.com', 1, 'Video delivery systems, popular in entertainment and news sites - SlyEWL')
(0, 'stackpath.bootstrapcdn.com', 1, 'Crucial CDN server - SlyEWL')
(0, 'staging.plex.tv', 1, 'Plex Media Server - SlyEWL')
(0, 'star-mini.c10r.facebook.com', 1, 'Facebook - SlyEWL')
(0, 'star.c10r.facebook.com', 1, 'Facebook - SlyEWL')
(0, 'static.ips.apple.com', 1, 'Apple - SlyEWL')
(0, 'static.opensubtitles.org', 1, 'Misc - SlyEWL')
(0, 'static.xx.fbcdn.net', 1, 'Facebook - Messenger - SlyEWL')
(0, 'statics.teams.cdn.office.net', 1, 'Microsoft - SlyEWL')
(0, 'stats.streamelements.com', 1, 'Misc - SlyEWL')
(0, 'status.plex.tv', 1, 'Plex Media Server - SlyEWL')
(0, 'stitcher.pluto.tv', 1, 'Pluto.tv - SlyEWL')
(0, 'storage.live.com', 1, 'Microsoft - SlyEWL')
(0, 'storage.signal.org', 1, 'Signal - SlyEWL')
(0, 'storeedgefd.dsx.mp.microsoft.com', 1, 'Microsoft Store - SlyEWL')
(0, 'streaming-fame.gammacdn.com', 1, 'AdultTime - Required to stream videos - SlyEWL')
(0, 'streaming-hls.gammacdn.com', 1, 'AdultTime - Required for streaming - SlyEWL')
(0, 'styles.redditmedia.com', 1, 'Reddit - SlyEWL')
(0, 'substrate.office.com', 1, 'Microsoft - SlyEWL')
(0, 'suconfig.apple.com', 1, 'Apple - SlyEWL')
(0, 'support.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'surveymonkey.com', 1, 'Misc - SlyEWL')
(0, 'swcdn.apple.com', 1, 'Apple - SlyEWL')
(0, 'swdist.apple.com', 1, 'Apple - SlyEWL')
(0, 'swdownload.apple.com', 1, 'Apple - SlyEWL')
(0, 'swpost.apple.com', 1, 'Apple - SlyEWL')
(0, 'swscan.apple.com', 1, 'Apple - SlyEWL')
(0, 'sylvan.apple.com', 1, 'Apple - SlyEWL')
(0, 'sysctl.org', 1, 'Misc - SlyEWL')
(0, 't.co', 1, 'Twitter - URL shortner - SlyEWL')
(0, 't.scdn.co', 1, 'Spotify - SlyEWL')
(0, 't0.ssl.ak.dynamic.tiles.virtualearth.net', 1, 'Microsoft - Used by Bing Maps to get information about various places - SlyEWL')
(0, 't0.ssl.ak.tiles.virtualearth.net', 1, 'Microsoft - Used by Bing Maps to get information about various places - SlyEWL')
(0, 'tagger.opecloud.com', 1, 'Misc - SlyEWL')
(0, 'tags.tiqcdn.com', 1, 'TDAmeritrade - SlyEWL')
(0, 'tawk.to', 1, 'Live chat platform for websites to chat with the website owner. Blocking this domain will block chat widget - SlyEWL')
(0, 'tbsc.apple.com', 1, 'Apple - SlyEWL')
(0, 'teams.events.data.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'teams.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'teams.office.com', 1, 'Microsoft - SlyEWL')
(0, 'tedcdn.com', 1, 'Used by ted.com streams - SlyEWL')
(0, 'telemetry-console.api.playstation.com', 1, 'Misc - SlyEWL')
(0, 'textsecure-service-whispersystems.org', 1, 'Misc - SlyEWL')
(0, 'themoviedb.com', 1, 'Plex Media Server - Metadata for movies - SlyEWL')
(0, 'thetvdb.com', 1, 'Plex Media Server - Metadata for TV series - SlyEWL')
(0, 'time-a.timefreq.bldrdoc.gov', 1, 'Sharp TV - SlyEWL')
(0, 'time-ios.apple.com', 1, 'Apple - SlyEWL')
(0, 'time-macos.apple.com', 1, 'Apple - SlyEWL')
(0, 'time.apple.com', 1, 'Apple - SlyEWL')
(0, 'time.samsungcloudsolution.com', 1, 'Samsung TV - SlyEWL')
(0, 'tinyurl.com', 1, 'URL Shortener - SlyEWL')
(0, 'title.mgt.xboxlive.com', 1, 'Microsoft Xbox - Used for Xbox updates, game downloads, acheivements - SlyEWL')
(0, 'tlu.dl.delivery.mp.microsoft.com', 1, 'Microsoft Store - SlyEWL')
(0, 'todo-ta-g7g.amazon.com', 1, 'Amazon - SlyEWL')
(0, 'tracking-protection.cdn.mozilla.net', 1, 'Firefox - SlyEWL')
(0, 'tracking.dpd.de', 1, 'Misc - SlyEWL')
(0, 'tracking.epicgames.com', 1, 'Epic Games - Required to make a purchase on the website - SlyEWL')
(0, 'traffic.libsyn.com', 1, 'Used in Pocketcasts app to serve and download podcasts - SlyEWL')
(0, 'trailers-fame.gammacdn.com', 1, 'AdultTime - A required domain of the site to access image, videos, etc - SlyEWL')
(0, 'transform.gammacdn.com', 1, 'AdultTime - Required to display recommended videos - SlyEWL')
(0, 'translate.google.com', 1, 'Google - SlyEWL')
(0, 'tsfe.trafficshaping.dsp.mp.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'tuner-api.hdhomerun.com', 1, 'SiliconDust HDHomeRun - Both required for firmware update - SlyEWL')
(0, 'turn1.whispersystems.org', 1, 'Misc - SlyEWL')
(0, 'tv.deezer.com', 1, 'HBBTV - SlyEWL')
(0, 'tv.scdn.co', 1, 'YouTube - Required for mobile devices to cast to android devices attached to your TV - SlyEWL')
(0, 'tvdb2.plex.tv', 1, 'Plex Media Server - SlyEWL')
(0, 'tvthemes.plexapp.com.cdn.cloudflare.net', 1, 'Plex Media Server - SlyEWL')
(0, 'twimg.com', 1, 'Twitter - Used to deliver media on Twitter - SlyEWL')
(0, 'twitter.com', 1, 'Twitter - SlyEWL')
(0, 'ubisoft-uplay-savegames.s3.amazonaws.com', 1, 'Ubisoft Launcher - Required for cloud saves - SlyEWL')
(0, 'ud-chat.signal.org', 1, 'Signal - SlyEWL')
(0, 'ui.skype.com', 1, 'Microsoft Skype - Used to make group calls, group chats etc. on Skype - SlyEWL')
(0, 'unagi-na.amazon.com', 1, 'Amazon - SlyEWL')
(0, 'unpkg.com', 1, 'Crucial CDN server - SlyEWL')
(0, 'unsplash.com', 1, 'Misc - SlyEWL')
(0, 'upcdn.b0.upaiyun.com', 1, 'Crucial CDN server - SlyEWL')
(0, 'update.biv.sony.tv', 1, 'Sony - SlyEWL')
(0, 'updates2.signal.org', 1, 'Signal - SlyEWL')
(0, 'upgrade.scdn.com', 1, 'Misc - SlyEWL')
(0, 'upload.appleschoolcontent.com', 1, 'Apple - SlyEWL')
(0, 'upload.facebook.com', 1, 'Facebook - SlyEWL')
(0, 'upload.fp.measure.office.com', 1, 'Microsoft - SlyEWL')
(0, 'upload.twitter.com', 1, 'Twitter - SlyEWL')
(0, 'us-east-1.amazonaws.com', 1, 'Amazon - SlyEWL')
(0, 'use.fontawesome.com', 1, 'Crucial CDN server - SlyEWL')
(0, 'use.fontawesome.com.cdn.cloudflare.net', 1, 'Crucial CDN server - SlyEWL')
(0, 'v.firebog.net', 1, 'Misc - SlyEWL')
(0, 'v.reddit.com', 1, 'Reddit - SlyEWL')
(0, 'v.shopify.com', 1, 'Shopping - SlyEWL')
(0, 'v.w-x.co', 1, 'Weather - SlyEWL')
(0, 'valid.apple.com', 1, 'Apple - SlyEWL')
(0, 'vcs.vdspf.com', 1, 'Panasonic Viera TV - SlyEWL')
(0, 'video-stats.l.google.com', 1, 'Google - Used to record YouTube watch history. Blocking this domain will pause your watch history on YouTube - SlyEWL')
(0, 'video.xx.fbcdn.net', 1, 'Facebook - Messenger - SlyEWL')
(0, 'videos.vidible.tv', 1, 'Video delivery systems, popular in entertainment and news sites - SlyEWL')
(0, 'videothumb.gammacdn.com', 1, 'AdultTime - Required to access video thumbnails - SlyEWL')
(0, 'vidtech.cbsinteractive.com', 1, 'Used to deliver videos over the internet - SlyEWL')
(0, 'vimeo.com', 1, 'Misc - SlyEWL')
(0, 'vjs.zencdn.net', 1, 'Crucial CDN server - SlyEWL')
(0, 'vlscppe.microsoft.com', 1, 'Microsoft - Required to download Windows 11 ISO file from the official MS website - SlyEWL')
(0, 'vo.aicdn.com', 1, 'Crucial CDN server - SlyEWL')
(0, 'vpp.itunes.apple.com', 1, 'Apple - SlyEWL')
(0, 'wa.me', 1, 'Misc - SlyEWL')
(0, 'watson.telemetry.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'web.facebook.com', 1, 'Facebook - SlyEWL')
(0, 'web.vortex.data.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'weblb-wg.dual-gslb.spotify.com', 1, 'Spotify - SlyEWL')
(0, 'weeklyad.target.com.edgesuite.net', 1, 'Target - SlyEWL')
(0, 'whispersystems-textsecure-attachments.s3-accelerate.amazonaws.com', 1, 'Amazon - SlyEWL')
(0, 'whiteboard.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'widget-cdn.rpxnow.com', 1, 'Akamai Technologies - Used as a sign in method in various apps and sites - SlyEWL')
(0, 'wikipedia.org', 1, 'Misc - SlyEWL')
(0, 'win10.ipv6.microsoft.com', 1, 'Gives full IPv6 connectivity for IPv6-capable hosts that are on the IPv4 Internet but have no native connection to an IPv6 network - SlyEWL')
(0, 'win10.prod.http1.netflix.com', 1, 'Netflix - Requried for signing in - SlyEWL')
(0, 'win1710.ipv6.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'winatp-gw-neu.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'windows.msn.com', 1, 'Microsoft Windows - Required to sign in to your account during a fresh installation - SlyEWL')
(0, 'winhelp2002.mvps.org', 1, 'Misc - SlyEWL')
(0, 'wl.spotify.com', 1, 'Spotify - SlyEWL')
(0, 'wordpress.com', 1, 'Wordpress - SlyEWL')
(0, 'wp.com', 1, 'WordPress - Site hosting service - SlyEWL')
(0, 'ws-ee-maidsvc.icloud.com', 1, 'Apple - SlyEWL')
(0, 'ws.audioscrobbler.com', 1, 'Plex Media Server - Last.fm; used to get track metadata using API - SlyEWL')
(0, 'ww.dataplicity.com', 1, 'Used to remotely control your Raspberry-Pi - SlyEWL')
(0, 'www.adf.ly', 1, 'URL Shortener - SlyEWL')
(0, 'www.aliexpress.com', 1, 'Shopping - SlyEWL')
(0, 'www.apple.com', 1, 'Apple - SlyEWL')
(0, 'www.appleiphonecell.com', 1, 'Apple - SlyEWL')
(0, 'www.asadcdn.com', 1, 'Misc - SlyEWL')
(0, 'www.dataplicity.com', 1, 'Misc - SlyEWL')
(0, 'www.ecdinterface.philips.com', 1, 'Philips TV - SlyEWL')
(0, 'www.facebook.com', 1, 'Facebook - SlyEWL')
(0, 'www.google-analytics.com', 1, 'Google - SlyEWL')
(0, 'www.googleapis.com', 1, 'Google - An important domain used to provide APIs to various Google services. - SlyEWL')
(0, 'www.howtogeek.com', 1, 'Misc - SlyEWL')
(0, 'www.icloud.com', 1, 'Apple - SlyEWL')
(0, 'www.itunes.com', 1, 'Apple - SlyEWL')
(0, 'www.linuxtracker.org', 1, 'Linux - SlyEWL')
(0, 'www.microsoft.com', 1, 'Microsoft - SlyEWL')
(0, 'www.msftconnecttest.com', 1, 'Microsoft - Used by Windows systems to check internet connectivity - SlyEWL')
(0, 'www.msftncsi.com', 1, 'Microsoft - This domain is checked by the operating systems when connecting via wifi, if no response, open wifi login page or similar - SlyEWL')
(0, 'www.no-ip.com', 1, 'NO-IP - Offers DNS services, email, network monitoring and SSL certificates - SlyEWL')
(0, 'www.opensubtitles.org', 1, 'Plex Media Server - SlyEWL')
(0, 'www.plex.tv', 1, 'Plex Media Server - SlyEWL')
(0, 'www.propublica.org', 1, 'Misc - SlyEWL')
(0, 'www.redditmedia.com', 1, 'Reddit - SlyEWL')
(0, 'www.redditstatic.com', 1, 'Reddit - SlyEWL')
(0, 'www.refersion.com', 1, 'Misc - SlyEWL')
(0, 'www.samsungotn.net', 1, 'Samsung TV - SlyEWL')
(0, 'www.signal.org', 1, 'Signal - SlyEWL')
(0, 'www.solaredge.com', 1, 'Misc - SlyEWL')
(0, 'www.squaretrade.com', 1, 'Shopping - SlyEWL')
(0, 'www.twitter.com', 1, 'Twitter - SlyEWL')
(0, 'www.vbsedit.com', 1, 'Safe website for learning to code in vbscript - SlyEWL')
(0, 'www.wa.me', 1, 'Misc - SlyEWL')
(0, 'www.xboxlive.com', 1, 'Microsoft Xbox - SlyEWL')
(0, 'www.youtube-nocookie.com', 1, 'Google YouTube - Privacy-Enhanced Mode. Used to embed the videos on third-party sites with less trackers - SlyEWL')
(0, 'x-default-stgec.uplynk.com', 1, 'DiscoveryPlus App - Required on Nvidia Shield TV - SlyEWL')
(0, 'xbox.ipv6.microsoft.com', 1, 'Microsoft Xbox - Used for Xbox updates, game downloads, acheivements - SlyEWL')
(0, 'xboxexperiencesprod.experimentation.xboxlive.com', 1, 'Microsoft Xbox - Used for Xbox updates, game downloads, acheivements - SlyEWL')
(0, 'xflight.xboxlive.com', 1, 'Microsoft Xbox - Used for Xbox updates, game downloads, acheivements - SlyEWL')
(0, 'xkms.xboxlive.com', 1, 'Microsoft Xbox - Used for Xbox updates, game downloads, acheivements - SlyEWL')
(0, 'xp-cdn.apple.com', 1, 'Apple - SlyEWL')
(0, 'xp.apple.com', 1, 'Apple - SlyEWL')
(0, 'yahoo.com', 1, 'Yahoo - SlyEWL')
(0, 'yandex.st', 1, 'Crucial CDN server - SlyEWL')
(0, 'yastatic.net', 1, 'Crucial CDN server - SlyEWL')
(0, 'youtu.be', 1, 'YouTube - URL Shortener - SlyEWL')
(0, 'youtube-nocookie.com', 1, 'Google YouTube - Privacy-Enhanced Mode; Used to embed the videos on third-party sites with less trackers - SlyEWL')
(0, 'youtube.com', 1, 'YouTube - SlyEWL')
(0, 'youtubei.googleapis.com', 1, 'YouTube - SlyEWL')
(0, 'yt3.ggpht.com', 1, 'Google YouTube - Used to deliver static files over the internet - SlyEWL')
(0, 'z.cdn.turner.com', 1, 'Turner - SlyEWL')
(0, 'zee.cws.conviva.com', 1, 'Conviva - Offers online video optimization and online video analytics. In order to watch many online contents you may need to whitelist. - SlyEWL')
(0, 'zeustracker.abuse.com', 1, 'Misc - SlyEWL')
