(1, 'a1241.dsct.akamai.net', 1, 'Akamai CDN Ad Server - SlyEBL')
(1, 'a21ed24aedde648804e7-228765c84088fef4ff5e70f2710398e9.r17.cf1.rackcdn.com', 1, 'Twitch Video Ads - SlyEBL')
(1, 'adserver-use1-ext-prod-a-563525597.us-east-1.elb.amazonaws.com', 1, 'Amazon CDN Ad Server - SlyEBL')
(1, 'aic-gfts.lge.com', 1, 'LG Smart TV - SlyEBL')
(1, 'aic-ngfts.lge.com', 1, 'LG Smart TV - SlyEBL')
(1, 'aic-op-lss.lgthinq.com', 1, 'LG Smart TV - SlyEBL')
(1, 'aic.api.lgtviot.com', 1, 'LG Smart TV - SlyEBL')
(1, 'aic.homeprv.lgtvcommon.com', 1, 'LG Smart TV - SlyEBL')
(1, 'aic.lgtviot.com', 1, 'LG Smart TV - SlyEBL')
(1, 'aic.nudge.lgtvcommon.com', 1, 'LG Smart TV - SlyEBL')
(1, 'aic.rdl.lgtvcommon.com', 1, 'LG Smart TV - SlyEBL')
(1, 'aic.recommend.lgtvcommon.com', 1, 'LG Smart TV - SlyEBL')
(1, 'aic.sports.lgtviot.com', 1, 'LG Smart TV - SlyEBL')
(1, 'aic.wiseconfig.lgtvcommon.com', 1, 'LG Smart TV - SlyEBL')
(1, 'api.itopvpn.com', 1, 'iTop VPN Telemetry - SlyEBL')
(1, 'api.nfl.com', 1, 'NFL - American Football Telemetry - SlyEBL')
(1, 'api.topaz-labs.net', 1, 'Topaz Labs Telemetry - SlyEBL')
(1, 'api.us-east-1.aiv-delivery.net', 1, 'LG Smart TV - SlyEBL')
(1, 'applytics.nordvpn.com', 1, 'NordVPN Telemetry - SlyEBL')
(1, 'bench.utorrent.com', 1, 'uTorrent Desktop App Ads- SlyEBL')
(1, 'canvas.tubitv.com', 1, 'LG Smart TV - SlyEBL')
(1, 'cc-api-data.adobe.io', 1, 'Adobe Systems Telemetry - SlyEBL')
(1, 'ccleaner.tools.avcdn.net', 1, 'CCleaner Telemetry Desktop App Spyware - SlyEBL')
(1, 'cdn.cookielaw.org', 1, '3D Mark Software tracking cookies - SlyEBL')
(1, 'cdn.inspectlet.com', 1, 'IObit Desktop Popup Advertisements - SlyEBL')
(1, 'cdn77.utomik.com', 1, 'LG Smart TV - SlyEBL')
(1, 'cf-trickplay.aux.pv-cdn.net', 1, 'LG Smart TV - SlyEBL')
(1, 'client-api.nordvpn.com', 1, 'NordVPN Telemetry - SlyEBL')
(1, 'cloudfront.xp-assets.aiv-cdn.net', 1, 'LG Smart TV - SlyEBL')
(1, 'codes.iobit.com', 1, 'IObit Desktop Pop up Ads - SlyEBL')
(1, 'common.lgthinq.com', 1, 'LG Smart TV - SlyEBL')
(1, 'cs833182181.wpc.etacdn.net', 1, 'IObit Desktop Pop-up Ads - SlyEBL')
(1, 'd186rixkn5ruba.cloudfront.net', 1, 'AdultTime Ads - SlyEBL')
(1, 'd1ut6fykkt3imt.cloudfront.net', 1, 'AdultTime Ads - SlyEBL')
(1, 'd20qwf0wrdtevy.cloudfront.net', 1, 'Cloudfront CDN Ad Server - SlyEBL')
(1, 'd2u28gf9o4d1cv.cloudfront.net', 1, 'Cloudfront CDN Ad Server - SlyEBL')
(1, 'd306ecvlh9tfv.cloudfront.net', 1, 'AdultTime Ads - SlyEBL')
(1, 'd3aqoihi2n8ty8.cloudfront.net', 1, 'AdultTime Ads - SlyEBL')
(1, 'd3cqix4sol87xw.cloudfront.net', 1, 'AdultTime Ads - SlyEBL')
(1, 'd3m1uefep57n8q.cloudfront.net', 1, 'Twitch Video Ads - SlyEBL')
(1, 'developers.google.com', 1, 'LG Smart TV - SlyEBL')
(1, 'discovery.meethue.com', 1, 'LG Smart TV - SlyEBL')
(1, 'dns-fxp05etdx.sombrero.yahoo.net', 1, 'Yahoo Video Ads - SlyEBL')
(1, 'doh.dns.apple.com', 1, 'Apple DoH Blocks Pi-Hole Queries Entirely - SlyEBL')
(1, 'doug1izaerwt3.cloudfront.net', 1, 'IObit Desktop Pop-up Ads - SlyEBL')
(1, 'dxtkri2c61io4.cloudfront.net', 1, 'Twitch Video Ads - SlyEBL')
(1, 'estore.iobit', 1, 'IObit Ads - SlyEBL')
(1, 'giveaway.iobit', 1, 'IObit Ads - SlyEBL')
(1, 'global.poe.live-video.net', 1, 'Twitch Video Ads - SlyEBL')
(1, 'gsn-rinkeby.redditspace.com', 1, 'Reddit Suspected Ads - SlyEBL')
(1, 'i.ibb.co', 1, 'LG Smart TV - SlyEBL')
(1, 'images.pluto.tv', 1, 'LG Smart TV - SlyEBL')
(1, 'images.redbox.com', 1, 'LG Smart TV - SlyEBL')
(1, 'img.nvidiagrid.net', 1, 'LG Smart TV - SlyEBL')
(1, 'ipv6.unagi-na.amazon.com', 1, 'LG Smart TV - SlyEBL')
(1, 'jc9wr0p5rbtco3ibchj4vnjz7z1lr1.ext-twitch.tv', 1, 'Twitch Video Ads - SlyEBL')
(1, 'kinesis.us-east-1.amazonaws.com', 1, 'AdultTime Ads - SlyEBL')
(1, 'lgtvonline.lge.com', 1, 'LG Smart TV - SlyEBL')
(1, 'lss.lgthinq.com', 1, 'LG Smart TV - SlyEBL')
(1, 'lynx-prod-beacon-alb-498367235.us-east-1.elb.amazonaws.com', 1, 'Amazon CDN Ad Server - SlyEBL')
(1, 'mediaservices.cdn-apple.com', 1, 'LG Smart TV - SlyEBL')
(1, 'mindfieldonline.com', 1, 'LG Smart TV - SlyEBL')
(1, 'munchkin.marketo.net', 1, '3D Mark Software Tracking Cookies - SlyEBL')
(1, 'ncp-gw-sports.media.yahoo.com', 1, 'Yahoo - Sports Video Ads - SlyEBL')
(1, 'nevoai-iothub-54-prod.azure-devices.net', 1, 'LG Smart TV - SlyEBL')
(1, 'ngfts.lge.com', 1, 'LG Smart TV - SlyEBL')
(1, 'ocsp.sca1b.amazontrust.com', 1, 'amazon.com Ads - SlyEBL')
(1, 'prod-elb-ats-620772989.us-east-1.elb.amazonaws.com', 1, 'Amazon CDN Ad Server - SlyEBL')
(1, 'prod.ups-ats.us-east-1.aolp-ds-prd.aws.oath.cloud', 1, 'Amazon CDN Ad Server - SlyEBL')
(1, 'purchase-iobit-com.us-east-1.elasticbeanstalk.com', 1, 'IObit Desktop Pop-up Ads - SlyEBL')
(1, 'purchase.iobit.com', 1, 'IObit Desktop Pop up Ads - SlyEBL')
(1, 'qt2-ngfts.lge.com', 1, 'LG Smart TV - SlyEBL')
(1, 'redirector.googlevideo.com', 1, 'Google Ads - SlyEBL')
(1, 's3-iad-2.cf.dash.row.aiv-cdn.net', 1, 'LG Smart TV - SlyEBL')
(1, 'service.idsync.analytics.yahoo.com', 1, 'LG Smart TV - SlyEBL')
(1, 'snap.licdn.com', 1, '3D Mark Software tracking cookies - SlyEBL')
(1, 'snu.lge.com', 1, 'LG Smart TV - SlyEBL')
(1, 'stats.iobit.com', 1, 'IObit Desktop Pop up Ads - SlyEBL')
(1, 'stats.itopvpn.com', 1, 'iTop VPN Telemetry - SlyEBL')
(1, 'store.iobit.com', 1, 'IObit Desktop Pop up Ads - SlyEBL')
(1, 'survey.iobit', 1, 'IObit Ads - SlyEBL')
(1, 'threeplr-avuypkjypveaj-0.api.amazonvideo.com', 1, 'LG Smart TV - SlyEBL')
(1, 'unagi-na.amazon.com', 1, 'LG Smart TV - SlyEBL')
(1, 'update.filesupdating.com', 1, 'iTop VPN Telemetry - SlyEBL')
(1, 'us.emp.lgsmartplatform.com', 1, 'LG Smart TV - SlyEBL')
(1, 'us.ibs.lgappstv.com', 1, 'LG Smart TV - SlyEBL')
(1, 'us.lgeapi.com', 1, 'LG Smart TV - SlyEBL')
(1, 'us.rdx2.lgtvsdp.com', 1, 'LG Smart TV - SlyEBL')
(1, 'usage.truenas.com', 1, 'TrueNAS Software Telemetry - SlyEBL')
(1, 'video-edge-55b156.pdx01.abs.hls.ttvnw.net', 1, 'Twitch Video Ads - SlyEBL')
(1, 'video-edge-6dca22.atl01.abs.hls.ttvnw.net', 1, 'Twitch Video Ads - SlyEBL')
(1, 'video-edge-833564.atl01.abs.hls.ttvnw.net', 1, 'Twitch Video Ads - SlyEBL')
(1, 'video-edge-8491b8.pdx01.abs.hls.ttvnw.net', 1, 'Twitch Video Ads - SlyEBL')
(1, 'video-weaver.atl01.hls.ttvnw.net', 1, 'Twitch Video Ads - SlyEBL')
(1, 'video-weaver.jfk04.hls.ttvnw.net', 1, 'Twitch Video Ads - SlyEBL')
(1, 'www.ueiwsp.com', 1, 'LG Smart TV - SlyEBL')
