(3, 'a1241.dsct.akamai.net', 1, 'Akamai CDN ad server - SlyEBL')
(3, 'a21ed24aedde648804e7-228765c84088fef4ff5e70f2710398e9.r17.cf1.rackcdn.com', 1, 'Twitch - Video ads - SlyEBL')
(3, 'adserver-use1-ext-prod-a-563525597.us-east-1.elb.amazonaws.com', 1, 'Amazon CDN ad server - SlyEBL')
(3, 'api.itopvpn.com', 1, 'iTop VPN Telemetry - SlyEBL')
(3, 'api.nfl.com', 1, 'NFL - American Football telemetry - SlyEBL')
(3, 'api.topaz-labs.net', 1, 'Topaz Labs telemetry - SlyEBL')
(3, 'applytics.nordvpn.com', 1, 'NordVPN telemetry - SlyEBL')
(3, 'cc-api-data.adobe.io', 1, 'Adobe Systems telemetry - SlyEBL')
(3, 'cdn.cookielaw.org', 1, '3D Mark Software tracking cookies - SlyEBL')
(3, 'client-api.nordvpn.com', 1, 'NordVPN telemetry - SlyEBL')
(3, 'd186rixkn5ruba.cloudfront.net', 1, 'AdultTime ads - SlyEBL')
(3, 'd1ut6fykkt3imt.cloudfront.net', 1, 'AdultTime ads - SlyEBL')
(3, 'd20qwf0wrdtevy.cloudfront.net', 1, 'Cloudfront CDN ad server - SlyEBL')
(3, 'd2u28gf9o4d1cv.cloudfront.net', 1, 'Cloudfront CDN ad server - SlyEBL')
(3, 'd306ecvlh9tfv.cloudfront.net', 1, 'AdultTime ads - SlyEBL')
(3, 'd3aqoihi2n8ty8.cloudfront.net', 1, 'AdultTime ads - SlyEBL')
(3, 'd3cqix4sol87xw.cloudfront.net', 1, 'AdultTime ads - SlyEBL')
(3, 'dns-fxp05etdx.sombrero.yahoo.net', 1, 'Yahoo video ads - SlyEBL')
(3, 'doh.dns.apple.com', 1, 'Apple DNS over HTTPS - Blocks pi-hole queries entirely - SlyEBL')
(3, 'estore.IObit', 1, 'IObit ads - SlyEBL')
(3, 'giveaway.IObit', 1, 'IObit ads - SlyEBL')
(3, 'global.poe.live-video.net', 1, 'Twitch Video ads - SlyEBL')
(3, 'gsn-rinkeby.redditspace.com', 1, 'Reddit suspected ads - SlyEBL')
(3, 'kinesis.us-east-1.amazonaws.com', 1, 'AdultTime ads - SlyEBL')
(3, 'lynx-prod-beacon-alb-498367235.us-east-1.elb.amazonaws.com', 1, 'Amazon CDN ad server - SlyEBL')
(3, 'm-node-alb-ssl-1111-1982902297.us-east-1.elb.amazonaws.com', 1, 'Amazon CDN ad server - SlyEBL')
(3, 'munchkin.marketo.net', 1, '3D Mark Software tracking cookies - SlyEBL')
(3, 'ncp-gw-sports.media.yahoo.com', 1, 'yahoo.com - sports video ads - SlyEBL')
(3, 'ocsp.sca1b.amazontrust.com', 1, 'amazon.com ads - SlyEBL')
(3, 'prod-elb-ats-620772989.us-east-1.elb.amazonaws.com', 1, 'Amazon CDN ad server - SlyEBL')
(3, 'prod.ups-ats.us-east-1.aolp-ds-prd.aws.oath.cloud', 1, 'Amazon CDN ad server - SlyEBL')
(3, 'redirector.googlevideo.com', 1, 'Google ads - SlyEBL')
(3, 'snap.licdn.com', 1, '3D Mark Software tracking cookies - SlyEBL')
(3, 'stats.itopvpn.com', 1, 'iTop VPN Telemetry - SlyEBL')
(3, 'survey.IObit', 1, 'IObit ads - SlyEBL')
(3, 'update.filesupdating.com', 1, 'iTop VPN Telemetry - SlyEBL')
(3, 'usage.truenas.com', 1, 'TrueNAS Software telemetry - SlyEBL')
(3, 'video-edge-830e74.atl01.abs.hls.ttvnw.net', 1, 'Twitch Video ads - SlyEBL')
(3, 'video-edge-8491b8.pdx01.abs.hls.ttvnw.net', 1, 'Twitch - Video ads - SlyEBL')
