(1, 'a21ed24aedde648804e7-228765c84088fef4ff5e70f2710398e9.r17.cf1.rackcdn.com', 1, 'twitch.tv - Video ads - SlyEWL')
(1, 'api.nfl.com', 1, 'NFL - American Football Telemetry - SlyEBL')
(1, 'api-software.qnap.com', 1, 'QNAP Computers Telemetry - SlyEBL')
(1, 'api.topaz-labs.net', 1, 'Topaz Labs Telemetry - SlyEBL')
(1, 'applytics.nordvpn.com', 1, 'NordVPN Telemetry - SlyEBL')
(1, 'cc-api-data.adobe.io', 1, 'Adobe Systems Telemetry - SlyEBL')
(1, 'client-api.nordvpn.com', 1, 'NordVPN Telemetry - SlyEBL')
(1, 'd186rixkn5ruba.cloudfront.net', 1, 'adulttime.com ads - SlyEBL')
(1, 'd1ut6fykkt3imt.cloudfront.net', 1, 'adulttime.com ads - SlyEBL')
(1, 'd-20p1an5qn.qnap.com', 1, 'QNAP Computers Telemetry - SlyEBL')
(1, 'd306ecvlh9tfv.cloudfront.net', 1, 'adulttime.com ads - SlyEBL')
(1, 'd3aqoihi2n8ty8.cloudfront.net', 1, 'adulttime.com ads - SlyEBL')
(1, 'd3cqix4sol87xw.cloudfront.net', 1, 'adulttime.com ads - SlyEBL')
(1, 'doh.dns.apple.com', 1, 'Apple DNS over HTTPS - Blocks pi-hole queries entirely - SlyEBL')
(1, 'estore.iobit.com', 1, 'iobit.com ads - SlyEBL')
(1, 'giveaway.iobit.com', 1, 'iobit.com ads - SlyEBL')
(1, 'global.poe.live-video.net', 1, 'twitch.tv Video ads - SlyEBL')
(1, 'iot.qnap.com', 1, 'QNAP Computers Telemetry - SlyEBL')
(1, 'ixq.qnap.com', 1, 'QNAP Computers Telemetry - SlyEBL')
(1, 'jlduihq7lrcdxgw4vrndhdfcsq.appsync-api.us-east-1.amazonaws.com', 1, 'adulttime.com ads - SlyEBL')
(1, 'kinesis.us-east-1.amazonaws.com', 1, 'adulttime.com ads - SlyEBL')
(1, 'kosmos-assets-prod.react.gammacdn.com', 1, 'adulttime.com ads - SlyEBL')
(1, 'marketing-materials.qnap.com', 1, 'QNAP Computers ads - SlyEBL')
(1, 'marketing.qnap.com', 1, 'QNAP Computers ads - SlyEBL')
(1, 'ncp-gw-sports.media.yahoo.com', 1, 'yahoo.com - sports video ads - SlyEBL')
(1, 'ocsp.sca1b.amazontrust.com', 1, 'amazon.com ads - SlyEBL')
(1, 'origin-marketing.qnap.com', 1, 'QNAP Computers ads - SlyEBL')
(1, 'origin-www.qnap.com', 1, 'QNAP Computers ads - SlyEBL')
(1, 'partner.qnap.com', 1, 'QNAP Computers ads - SlyEBL')
(1, 'survey.iobit.com', 1, 'iobit.com ads - SlyEBL')
(1, 'video-edge-046b4c.atl01.abs.hls.ttvnw.net', 1, 'twitch.tv Video ads - SlyEBL')
(1, 'video-edge-078ff6.atl01.abs.hls.ttvnw.net', 1, 'twitch.tv Video ads - SlyEBL')
(1, 'video-edge-82d760.atl01.abs.hls.ttvnw.net', 1, 'twitch.tv Video ads - SlyEBL')
(1, 'video-edge-82dc48.atl01.abs.hls.ttvnw.net', 1, 'twitch.tv - Video ads - SlyEWL')
(1, 'video-edge-830164.atl01.abs.hls.ttvnw.net', 1, 'twitch.tv - Video ads - SlyEWL')
(1, 'video-edge-833564.atl01.abs.hls.ttvnw.net', 1, 'twitch.tv Video ads - SlyEBL')
(1, 'video-edge-8491b8.pdx01.abs.hls.ttvnw.net', 1, 'twitch.tv - Video ads - SlyEWL')
(1, 'video-edge-918014.atl01.abs.hls.ttvnw.net', 1, 'twitch.tv Video ads - SlyEBL')
(1, 'video-edge-918388.atl01.abs.hls.ttvnw.net', 1, 'twitch.tv - Video ads - SlyEWL')
(1, 'video-edge-9183d4.atl01.abs.hls.ttvnw.net', 1, 'twitch.tv Video ads - SlyEBL')
(1, 'video-edge-9183f0.atl01.abs.hls.ttvnw.net', 1, 'twitch.tv Video ads - SlyEBL')
