// This is a backup of all exact whitelists that I have replaced with other filters (mainly using regex).

(1, 'usage-eu-fy2014.myhomescreen.tv', 1, 'Panasonic - SlyEBL')
(1, 'usage-eu-fy2015.myhomescreen.tv', 1, 'Panasonic - SlyEBL')
(1, 'usage-eu-fy2016.myhomescreen.tv', 1, 'Panasonic - SlyEBL')
(1, 'usage-eu-fy2017.myhomescreen.tv', 1, 'Panasonic - SlyEBL')
(1, 'usage-eu-fy2018.myhomescreen.tv', 1, 'Panasonic - SlyEBL')
(1, 'usage-eu-fy2019.myhomescreen.tv', 1, 'Panasonic - SlyEBL')
(1, 'usage-eu-fy2020.myhomescreen.tv', 1, 'Panasonic - SlyEBL')
(1, 'usage-us-fy2014.myhomescreen.tv', 1, 'Panasonic - SlyEBL')
(1, 'usage-us-fy2015.myhomescreen.tv', 1, 'Panasonic - SlyEBL')
(1, 'usage-us-fy2016.myhomescreen.tv', 1, 'Panasonic - SlyEBL')
(1, 'usage-us-fy2017.myhomescreen.tv', 1, 'Panasonic - SlyEBL')
(1, 'usage-us-fy2018.myhomescreen.tv', 1, 'Panasonic - SlyEBL')
(1, 'usage-us-fy2019.myhomescreen.tv', 1, 'Panasonic - SlyEBL')
(1, 'usage-us-fy2020.myhomescreen.tv', 1, 'Panasonic - SlyEBL')
