(0, '0-edge-chat.facebook.com', 1, 'sly9zk')
(0, '0.client-channel.google.com', 1, 'sly9zk')
(0, '1-edge-chat.facebook.com', 1, 'sly9zk')
(0, '1drv.com', 1, 'sly9zk')
(0, '2-edge-chat.facebook.com', 1, 'sly9zk')
(0, '2.android.pool.ntp.org', 1, 'sly9zk')
(0, '3-edge-chat.facebook.com', 1, 'sly9zk')
(0, '4-edge-chat.facebook.com', 1, 'sly9zk')
(0, '5-edge-chat.facebook.com', 1, 'sly9zk')
(0, '6-edge-chat.facebook.com', 1, 'sly9zk')
(0, 'activate.adobe.com', 1, 'sly9zk')
(0, 'adf.ly', 1, 'sly9zk')
(0, 'ae01.alicdn.com', 1, 'sly9zk')
(0, 'akamaihd.net', 1, 'sly9zk')
(0, 'akamaitechnologies.com', 1, 'sly9zk')
(0, 'akamaized.net', 1, 'sly9zk')
(0, 'albert.apple.com', 1, 'Device activation. - sly9zk')
(0, 'alluremedia.com', 1, 'sly9zk')
(0, 'amazonaws.com', 1, 'sly9zk')
(0, 'amd.cdn.turner.com', 1, 'sly9zk')
(0, 'amzn.com', 1, 'sly9zk')
(0, 'amzn.to', 1, 'sly9zk')
(0, 'android.clients.google.com', 1, 'sly9zk')
(0, 'announcements.vizio.com', 1, 'sly9zk')
(0, 'api-global.netflix.com', 1, 'sly9zk')
(0, 'api-tv.spotify.com', 1, 'sly9zk')
(0, 'api.accuweather.com', 1, 'sly9zk')
(0, 'api.euro.hismarttv.com', 1, 'sly9zk')
(0, 'api.ipify.org', 1, 'sly9zk')
(0, 'api.pluto.tv # Pluto.tv', 1, 'sly9zk')
(0, 'api.pluto.tv', 1, 'sly9zk')
(0, 'api.us.hismarttv.com', 1, 'sly9zk')
(0, 'api.vizio.com', 1, 'sly9zk')
(0, 'apicache.vudu.com', 1, 'sly9zk')
(0, 'app-api.ted.com', 1, 'sly9zk')
(0, 'app.emby.', 1, 'sly9zk')
(0, 'app.plex.tv', 1, 'sly9zk')
(0, 'appboot.netflix.com', 1, 'sly9zk')
(0, 'appldnld.apple.com', 1, 'iOS updates. - sly9zk')
(0, 'appleid.apple.com', 1, 'sly9zk')
(0, 'applicast.ga.sony.net', 1, 'sly9zk')
(0, 'apps.skype.com', 1, 'sly9zk')
(0, 'appsbackup-pa.clients6.google.com', 1, 'sly9zk')
(0, 'appsbackup-pa.googleapis.com', 1, 'sly9zk')
(0, 'apresolve.spotify.com', 1, 'sly9zk')
(0, 'apt.sonarr.tv', 1, 'sly9zk')
(0, 'aspnetcdn.com', 1, 'sly9zk')
(0, 'attestation.xboxlive.com', 1, 'sly9zk')
(0, 'auth.samsungosp.com', 1, 'sly9zk')
(0, 'avpro.global.yamaha.com', 1, 'sly9zk')
(0, 'aws.amazon.com', 1, 'sly9zk')
(0, 'ax.phobos.apple.com.edgesuite.net', 1, 'sly9zk')
(0, 'best.aliexpress.com', 1, 'sly9zk')
(0, 'bing.com', 1, 'sly9zk')
(0, 'bit.ly', 1, 'sly9zk')
(0, 'brightcove.net', 1, 'sly9zk')
(0, 'bufferapp.com', 1, 'sly9zk')
(0, 'bugmenot.com', 1, 'sly9zk')
(0, 'c.s-microsoft.com', 1, 'sly9zk')
(0, 'captive.apple.com', 1, 'Internet connectivity validation for networks that use captive portals. - sly9zk')
(0, 'cdn-mobile.api.pluto.tv', 1, 'sly9zk')
(0, 'cdn.cloudflare.net', 1, 'sly9zk')
(0, 'cdn.embedly.com', 1, 'sly9zk')
(0, 'cdn.fbsbx.com', 1, 'sly9zk')
(0, 'cdn.optimizely.com', 1, 'sly9zk')
(0, 'cdn.refersion.com', 1, 'sly9zk')
(0, 'cdn.samsungcloudsolution.com', 1, 'sly9zk')
(0, 'cdn.vidible.tv', 1, 'sly9zk')
(0, 'cdn2.optimizely.com', 1, 'sly9zk')
(0, 'cdn3.optimizely.com', 1, 'sly9zk')
(0, 'cdnjs.cloudflare.com', 1, 'sly9zk')
(0, 'cert.mgt.xboxlive.com', 1, 'sly9zk')
(0, 'cf.iadsdk.apple.com', 1, 'sly9zk')
(0, 'clientconfig.passport.net', 1, 'sly9zk')
(0, 'clients3.google.com', 1, 'sly9zk')
(0, 'clients5.google.com', 1, 'sly9zk')
(0, 'clients6.google.com', 1, 'sly9zk')
(0, 'cognito-identity.us-east-1.amazonaws.com', 1, 'sly9zk')
(0, 'configuration.apple.com', 1, 'Rosetta 2 updates. - sly9zk')
(0, 'connecttv.pelmorex.com', 1, 'sly9zk')
(0, 'cpms.spop10.ams.plex.bz', 1, 'sly9zk')
(0, 'cpms35.spop10.ams.plex.bz', 1, 'sly9zk')
(0, 'creative.ak.fbcdn.net', 1, 'sly9zk')
(0, 'crl.apple.com', 1, 'Security certificate validation. - sly9zk')
(0, 'crl.entrust.net', 1, 'Security certificate validation. - sly9zk')
(0, 'crl3.digicert.com', 1, 'Security certificate validation. - sly9zk')
(0, 'crl4.digicert.com', 1, 'Security certificate validation. - sly9zk')
(0, 'cse.google.com', 1, 'sly9zk')
(0, 'ctldl.windowsupdate.com', 1, 'sly9zk')
(0, 'd1oxlq5h9kq8q5.cloudfront.net', 1, 'sly9zk')
(0, 'd2c8v52ll5s99u.cloudfront.net', 1, 'sly9zk')
(0, 'd2gatte9o95jao.cloudfront.net', 1, 'sly9zk')
(0, 'dashboard.plex.tv', 1, 'sly9zk')
(0, 'dataplicity.com', 1, 'sly9zk')
(0, 'def-vef.xboxlive.com', 1, 'sly9zk')
(0, 'delivery.vidible.tv', 1, 'sly9zk')
(0, 'det-ta-g7g.amazon.com', 1, 'sly9zk')
(0, 'dev.virtualearth.net', 1, 'sly9zk')
(0, 'device-messaging-na.amazon.com', 1, 'sly9zk')
(0, 'device.auth.xboxlive.com', 1, 'sly9zk')
(0, 'deviceenrollment.apple.com', 1, 'DEP provisional enrollment. - sly9zk')
(0, 'deviceportal.nettvservices.com', 1, 'sly9zk')
(0, 'deviceservices-external.apple.com', 1, 'sly9zk')
(0, 'diagassets.apple.com', 1, 'Used by Apple devices to help detect possible hardware issues. - sly9zk')
(0, 'display.ugc.bazaarvoice.com', 1, 'sly9zk')
(0, 'displaycatalog.mp.microsoft.com', 1, 'sly9zk')
(0, 'dl.delivery.mp.microsoft.com', 1, 'sly9zk')
(0, 'dl.dropbox.com', 1, 'sly9zk')
(0, 'dl.dropboxusercontent.com', 1, 'sly9zk')
(0, 'dns.msftncsi.com', 1, 'sly9zk')
(0, 'download.sonarr.tv', 1, 'sly9zk')
(0, 'drift.com', 1, 'sly9zk')
(0, 'driftt.com', 1, 'sly9zk')
(0, 'drscdn.500px.org', 1, 'sly9zk')
(0, 'dsms0mj1bbhn4.cloudfront.net', 1, 'sly9zk')
(0, 'dynupdate.no-ip.com', 1, 'sly9zk')
(0, 'ea.com', 1, 'sly9zk')
(0, 'ec-ns.sascdn.com', 1, 'sly9zk')
(0, 'ecn.dev.virtualearth.net', 1, 'sly9zk')
(0, 'edge-chat.facebook.com', 1, 'sly9zk')
(0, 'edge-mqtt.facebook.com', 1, 'sly9zk')
(0, 'edge.api.brightcove.com', 1, 'sly9zk')
(0, 'eds.xboxlive.com', 1, 'sly9zk')
(0, 'epg.corio.com', 1, 'sly9zk')
(0, 'events.gfe.nvidia.com', 1, 'sly9zk')
(0, 'external-lhr0-1.xx.fbcdn.net', 1, 'sly9zk')
(0, 'external-lhr1-1.xx.fbcdn.net', 1, 'sly9zk')
(0, 'external-lhr10-1.xx.fbcdn.net', 1, 'sly9zk')
(0, 'external-lhr2-1.xx.fbcdn.net', 1, 'sly9zk')
(0, 'external-lhr3-1.xx.fbcdn.net', 1, 'sly9zk')
(0, 'external-lhr4-1.xx.fbcdn.net', 1, 'sly9zk')
(0, 'external-lhr5-1.xx.fbcdn.net', 1, 'sly9zk')
(0, 'external-lhr6-1.xx.fbcdn.net', 1, 'sly9zk')
(0, 'external-lhr7-1.xx.fbcdn.net', 1, 'sly9zk')
(0, 'external-lhr8-1.xx.fbcdn.net', 1, 'sly9zk')
(0, 'external-lhr9-1.xx.fbcdn.net', 1, 'sly9zk')
(0, 'facebook.com', 1, 'sly9zk')
(0, 'facebook.net', 1, 'sly9zk')
(0, 'fbcdn-creative-a.akamaihd.net', 1, 'sly9zk')
(0, 'fbcdn.net', 1, 'sly9zk')
(0, 'filament.io', 1, 'sly9zk')
(0, 'fivethirtyeight.com', 1, 'sly9zk')
(0, 'fonts.gstatic.com', 1, 'sly9zk')
(0, 'forms.', 1, 'sly9zk')
(0, 'forms.office.com', 1, 'sly9zk')
(0, 'forums.sonarr.tv', 1, 'sly9zk')
(0, 'fs.microsoft.com', 1, 'sly9zk')
(0, 'g.live.com', 1, 'sly9zk')
(0, 'gdmf.apple.com', 1, 'Used by an MDM server to identify which software updates are available to devices that use managed software updates. - sly9zk')
(0, 'geo-prod.do.dsp.mp.microsoft.com', 1, 'sly9zk')
(0, 'geo.opera.com', 1, 'sly9zk')
(0, 'geo3.ggpht.com', 1, 'sly9zk')
(0, 'gfwsl.geforce.com', 1, 'sly9zk')
(0, 'gg.apple.com', 1, 'iOS, tvOS, and macOS updates. - sly9zk')
(0, 'giphy.com', 1, 'sly9zk')
(0, 'github.com', 1, 'sly9zk')
(0, 'github.io', 1, 'sly9zk')
(0, 'gnf-mdn.apple.com', 1, 'macOS updates. - sly9zk')
(0, 'gnf-mr.apple.com', 1, 'macOS updates. - sly9zk')
(0, 'goo.', 1, 'sly9zk')
(0, 'goo.gl', 1, 'sly9zk')
(0, 'googleapis.com', 1, 'sly9zk')
(0, 'graph.facebook.com', 1, 'sly9zk')
(0, 'graph.instagram.com', 1, 'sly9zk')
(0, 'graph.oculus.com', 1, 'sly9zk')
(0, 'gravatar.com', 1, 'sly9zk')
(0, 'gs.apple.com', 1, 'macOS updates. - sly9zk')
(0, 'gstatic.com', 1, 'sly9zk')
(0, 'hbbtv.prosieben.de', 1, 'sly9zk')
(0, 'hbbtv.redbutton.de', 1, 'sly9zk')
(0, 'hbbtv.zdf.de', 1, 'sly9zk')
(0, 'heartbeat.dm.origin.com', 1, 'sly9zk')
(0, 'help.ui.xboxlive.com', 1, 'sly9zk')
(0, 'hls.ted.com', 1, 'sly9zk')
(0, 'hosts-file.net', 1, 'sly9zk')
(0, 'hostsfile.mine.', 1, 'sly9zk')
(0, 'hostsfile.mine.nu', 1, 'sly9zk')
(0, 'hostsfile.org', 1, 'sly9zk')
(0, 'humb.apple.com', 1, 'sly9zk')
(0, 'i.cdn.turner.com', 1, 'sly9zk')
(0, 'i.s-microsoft.com', 1, 'sly9zk')
(0, 'i.ytimg.com', 1, 'sly9zk')
(0, 'i1.ytimg.com', 1, 'sly9zk')
(0, 'iadsdk.apple.com', 1, 'sly9zk')
(0, 'identity.apple.com', 1, 'APNs certificate request portal. - sly9zk')
(0, 'ig.apple.com', 1, 'macOS updates. - sly9zk')
(0, 'images.pluto.tv', 1, 'sly9zk')
(0, 'images.vizio.com', 1, 'sly9zk')
(0, 'imagesak.secureserver.net', 1, 'sly9zk')
(0, 'img.vidible.tv', 1, 'sly9zk')
(0, 'imgix.net', 1, 'sly9zk')
(0, 'imgs.xkcd.com', 1, 'sly9zk')
(0, 'infolink.pavv.co.kr', 1, 'sly9zk')
(0, 'instagram.c10r.facebook.com', 1, 'sly9zk')
(0, 'intercom.io', 1, 'sly9zk')
(0, 'iprofiles.apple.com', 1, 'Hosts enrollment profiles used when devices enroll in Apple School Manager or Apple Business Manager through Device Enrollment. - sly9zk')
(0, 'isu.apple.com', 1, 'sly9zk')
(0, 'itunes-apple.com.akadns.net', 1, 'sly9zk')
(0, 'itunes.apple.com', 1, 'App Store - sly9zk')
(0, 'itunes.apple.com.edgesuite.net', 1, 'sly9zk')
(0, 'itunes.com', 1, 'sly9zk')
(0, 'itv.ard.de', 1, 'sly9zk')
(0, 'j.mp', 1, 'sly9zk')
(0, 'jquery.com', 1, 'sly9zk')
(0, 'jsdelivr.net', 1, 'sly9zk')
(0, 'keystone.mwbsys.com', 1, 'sly9zk')
(0, 'lastfm-img2.akamaized.net', 1, 'sly9zk')
(0, 'lcdn-registration.apple.com', 1, 'sly9zk')
(0, 'lcprd1.samsungcloudsolution.net', 1, 'sly9zk')
(0, 'licensing.xboxlive.com', 1, 'sly9zk')
(0, 'linkedin.com', 1, 'sly9zk')
(0, 'linuxtracker.org', 1, 'sly9zk')
(0, 'live.com', 1, 'sly9zk')
(0, 'lm.licenses.adobe.com', 1, 'sly9zk')
(0, 'location-api.hdhomerun.com', 1, 'sly9zk')
(0, 'login.aliexpress.com', 1, 'sly9zk')
(0, 'login.live.com', 1, 'sly9zk')
(0, 'login.microsoftonline.com', 1, 'sly9zk')
(0, 'm.hotmail.com', 1, 'sly9zk')
(0, 'm.youtube.com', 1, 'sly9zk')
(0, 'manifest.googlevideo.com', 1, 'sly9zk')
(0, 'market.spotify.com', 1, 'sly9zk')
(0, 'mdmenrollment.apple.com', 1, 'MDM servers to upload enrollment profiles used by clients enrolling through Device Enrollment in Apple School Manager or Apple Business Manager, and to look up devices and accounts. - sly9zk')
(0, 'medium.com', 1, 'sly9zk')
(0, 'mesu.apple.com', 1, 'Hosts software update catalogs. - sly9zk')
(0, 'meta-db-worker02.pop.ric.plex.bz', 1, 'sly9zk')
(0, 'meta.plex.bz', 1, 'sly9zk')
(0, 'meta.plex.tv', 1, 'sly9zk')
(0, 'mhc-ajax-eu-s2.myhomescreen.tv', 1, 'sly9zk')
(0, 'mhc-ajax-eu.myhomescreen.tv', 1, 'sly9zk')
(0, 'mhc-ajax-us.myhomescreen.tv', 1, 'sly9zk')
(0, 'mhc-eu.myhomescreen.tv', 1, 'sly9zk')
(0, 'mhc-us.myhomescreen.tv', 1, 'sly9zk')
(0, 'mhc-xpana-eu-s2.myhomescreen.tv', 1, 'sly9zk')
(0, 'mhc-xpana-eu.myhomescreen.tv', 1, 'sly9zk')
(0, 'mhc-xpana-us.myhomescreen.tv', 1, 'sly9zk')
(0, 'microsoft.com', 1, 'sly9zk')
(0, 'microsoftonline.com', 1, 'sly9zk')
(0, 'mobile-ap.spotify.com', 1, 'sly9zk')
(0, 'mobile.pipe.aria.microsoft.com', 1, 'sly9zk')
(0, 'mqtt-mini.facebook.com', 1, 'sly9zk')
(0, 'msftncsi.com', 1, 'sly9zk')
(0, 'my.plexapp.com', 1, 'sly9zk')
(0, 'netflix.com', 1, 'sly9zk')
(0, 'news.iadsdk.apple.com', 1, 'sly9zk')
(0, 'nexusrules.officeapps.live.com', 1, 'sly9zk')
(0, 'ngfts.lge.com', 1, 'sly9zk')
(0, 'nine.plugins.plexapp.com', 1, 'sly9zk')
(0, 'no-ip.com', 1, 'sly9zk')
(0, 'node.plexapp.com', 1, 'sly9zk')
(0, 'notify.xboxlive.com', 1, 'sly9zk')
(0, 'nrdp.nccp.netflix.com', 1, 'sly9zk')
(0, 'ns.itunes.apple.com', 1, 'sly9zk')
(0, 'ns1.dropbox.com', 1, 'sly9zk')
(0, 'ns11.whois.co.kr', 1, 'sly9zk')
(0, 'ns2.dropbox.com', 1, 'sly9zk')
(0, 'o1.email.plex.tv', 1, 'sly9zk')
(0, 'o2.sg0.plex.tv', 1, 'sly9zk')
(0, 'ocsp.apple.com', 1, 'Security certificate validation. - sly9zk')
(0, 'ocsp.apple.com', 1, 'sly9zk')
(0, 'ocsp.digicert.com', 1, 'Security certificate validation. - sly9zk')
(0, 'ocsp.entrust.net', 1, 'Security certificate validation. - sly9zk')
(0, 'ocsp.rootg2.amazontrust.com', 1, 'sly9zk')
(0, 'ocsp.verisign.net', 1, 'Security certificate validation. - sly9zk')
(0, 'office.com', 1, 'sly9zk')
(0, 'office.net', 1, 'sly9zk')
(0, 'office365.com', 1, 'sly9zk')
(0, 'officeclient.microsoft.com', 1, 'sly9zk')
(0, 'om.cbsi.com', 1, 'sly9zk')
(0, 'onedrive.live.com', 1, 'sly9zk')
(0, 'osb-ussvc.samsungqbe.com', 1, 'sly9zk')
(0, 'oscdn.apple.com', 1, 'macOS Recovery - sly9zk')
(0, 'osrecovery.apple.com', 1, 'macOS Recovery - sly9zk')
(0, 'ota-downloads.nvidia.com', 1, 'sly9zk')
(0, 'otn.samsungcloudcdn.com', 1, 'sly9zk')
(0, 'otnprd10.samsungcloudsolution.net', 1, 'sly9zk')
(0, 'otnprd11.samsungcloudsolution.net', 1, 'sly9zk')
(0, 'otnprd8.samsungcloudsolution.net', 1, 'sly9zk')
(0, 'otnprd9.samsungcloudsolution.net', 1, 'sly9zk')
(0, 'outlook.live.com', 1, 'sly9zk')
(0, 'outlook.office365.com', 1, 'sly9zk')
(0, 'ow.ly', 1, 'sly9zk')
(0, 'pgl.yoyo.org', 1, 'sly9zk')
(0, 'pinterest.com', 1, 'sly9zk')
(0, 'placehold.it', 1, 'sly9zk')
(0, 'placeholdit.imgix.net', 1, 'sly9zk')
(0, 'platform.cid.samba.tv', 1, 'sly9zk')
(0, 'players.brightcove.net', 1, 'sly9zk')
(0, 'players.pluto.tv', 1, 'sly9zk')
(0, 'plex.tv', 1, 'sly9zk')
(0, 'pmd.cdn.turner.com', 1, 'sly9zk')
(0, 'portal.store.sonyentertainmentnetwork.com', 1, 'sly9zk')
(0, 'ppq.apple.com', 1, 'Enterprise App validation - sly9zk')
(0, 'pricelist.skype.com', 1, 'sly9zk')
(0, 'prod.telemetry.ros.rockstargames.com', 1, 'sly9zk')
(0, 'products.office.com', 1, 'sly9zk')
(0, 'proxy.plex.bz', 1, 'sly9zk')
(0, 'proxy.plex.tv', 1, 'sly9zk')
(0, 'proxy02.pop.ord.plex.bz', 1, 'sly9zk')
(0, 'pubsub.plex.bz', 1, 'sly9zk')
(0, 'pubsub.plex.tv', 1, 'sly9zk')
(0, 'radarsubmissions.apple.com', 1, 'sly9zk')
(0, 'raw.githubusercontent.com', 1, 'sly9zk')
(0, 'reddit.com', 1, 'sly9zk')
(0, 'redirector.googlevideo.com', 1, 'sly9zk')
(0, 'refersion.com', 1, 'sly9zk')
(0, 'res.cloudinary.com', 1, 'sly9zk')
(0, 'rover.ebay.com', 1, 'sly9zk')
(0, 's.cdn.turner.com', 1, 'sly9zk')
(0, 's.gateway.messenger.live.com', 1, 'sly9zk')
(0, 's.marketwatch.com', 1, 'sly9zk')
(0, 's.shopify.com', 1, 'sly9zk')
(0, 's.youtube.com', 1, 'sly9zk')
(0, 's.ytimg.com', 1, 'sly9zk')
(0, 's1.wp.com', 1, 'sly9zk')
(0, 's2.youtube.com', 1, 'sly9zk')
(0, 's3-eu-west-1.amazonaws.com', 1, 'sly9zk')
(0, 's3.amazonaws.com', 1, 'sly9zk')
(0, 'sa.symcb.com', 1, 'sly9zk')
(0, 'samsungosp.com', 1, 'sly9zk')
(0, 'samsungotn.net', 1, 'sly9zk')
(0, 'scontent-lhr3-1.xx.fbcdn.net', 1, 'sly9zk')
(0, 'scontent.fgdl5-1.fna.fbcdn.net', 1, 'sly9zk')
(0, 'scontent.xx.fbcdn.net', 1, 'sly9zk')
(0, 'secure.netflix.com', 1, 'sly9zk')
(0, 'secure.surveymonkey.com', 1, 'sly9zk')
(0, 'serverstatus.apple.com', 1, 'Content caching client public IP determination - sly9zk')
(0, 'services.sonarr.tv', 1, 'sly9zk')
(0, 'setup.icloud.com', 1, 'Required to log in with a Managed Apple ID on Shared iPad. - sly9zk')
(0, 'shareaholic.com', 1, 'sly9zk')
(0, 'sharepoint.com', 1, 'sly9zk')
(0, 'silo.pluto.tv', 1, 'sly9zk')
(0, 'siloh.pluto.tv', 1, 'sly9zk')
(0, 'skl.apple.com', 1, 'macOS updates. - sly9zk')
(0, 'skyhook.sonarr.tv', 1, 'sly9zk')
(0, 'skype.com', 1, 'sly9zk')
(0, 'society6.com', 1, 'sly9zk')
(0, 'someonewhocares.org', 1, 'sly9zk')
(0, 'spclient-wg.spotify.com', 1, 'sly9zk')
(0, 'spclient.wg.spotify.com', 1, 'sly9zk')
(0, 'sq-device.apple.com', 1, 'eSIM activation - sly9zk')
(0, 'ssl.google-analytics.com', 1, 'sly9zk')
(0, 'ssl.p.jwpcdn.com', 1, 'sly9zk')
(0, 'staging.plex.tv', 1, 'sly9zk')
(0, 'static.ips.apple.com', 1, 'sly9zk')
(0, 'static.opensubtitles.org', 1, 'sly9zk')
(0, 'stats.streamelements.com', 1, 'sly9zk')
(0, 'status.plex.tv', 1, 'sly9zk')
(0, 'stitcher.pluto.tv', 1, 'sly9zk')
(0, 'support.microsoft.com', 1, 'sly9zk')
(0, 'surveymonkey.com', 1, 'sly9zk')
(0, 'swcdn.apple.com', 1, 'macOS updates. - sly9zk')
(0, 'swdist.apple.com', 1, 'macOS updates. - sly9zk')
(0, 'swdownload.apple.com', 1, 'macOS updates. - sly9zk')
(0, 'swpost.apple.com', 1, 'macOS updates. - sly9zk')
(0, 'swscan.apple.com', 1, 'macOS updates. - sly9zk')
(0, 'sysctl.org', 1, 'sly9zk')
(0, 't0.ssl.ak.dynamic.tiles.virtualearth.net', 1, 'sly9zk')
(0, 't0.ssl.ak.tiles.virtualearth.net', 1, 'sly9zk')
(0, 'tawk.to', 1, 'sly9zk')
(0, 'tbsc.apple.com', 1, 'sly9zk')
(0, 'tedcdn.com', 1, 'sly9zk')
(0, 'themoviedb.com', 1, 'sly9zk')
(0, 'thetvdb.com', 1, 'sly9zk')
(0, 'time-a.timefreq.bldrdoc.gov', 1, 'sly9zk')
(0, 'time-ios.apple.com', 1, 'Used by devices to set their date and time. - sly9zk')
(0, 'time-macos.apple.com', 1, 'Used by devices to set their date and time. - sly9zk')
(0, 'time.apple.com', 1, 'Used by devices to set their date and time. - sly9zk')
(0, 'time.samsungcloudsolution.com', 1, 'sly9zk')
(0, 'tinyurl.com', 1, 'sly9zk')
(0, 'title.auth.xboxlive.com', 1, 'sly9zk')
(0, 'title.mgt.xboxlive.com', 1, 'sly9zk')
(0, 'todo-ta-g7g.amazon.com', 1, 'sly9zk')
(0, 'tuner-api.hdhomerun.com', 1, 'sly9zk')
(0, 'tv.deezer.com', 1, 'sly9zk')
(0, 'tvdb2.plex.tv', 1, 'sly9zk')
(0, 'tvthemes.plexapp.com', 1, 'sly9zk')
(0, 'twimg.com', 1, 'sly9zk')
(0, 'twitter.com', 1, 'sly9zk')
(0, 'ui.skype.com', 1, 'sly9zk')
(0, 'unagi-na.amazon.com', 1, 'sly9zk')
(0, 'unsplash.com', 1, 'sly9zk')
(0, 'update.biv.sony.tv', 1, 'sly9zk')
(0, 'updates-http.cdn-apple.com', 1, 'sly9zk')
(0, 'updates.cdn-apple.com', 1, 'sly9zk')
(0, 'upgrade.scdn.', 1, 'sly9zk')
(0, 'upgrade.scdn.com', 1, 'sly9zk')
(0, 'us-east-1.amazonaws.com', 1, 'sly9zk')
(0, 'v.firebog.net', 1, 'sly9zk')
(0, 'v.shopify.com', 1, 'sly9zk')
(0, 'v10.events.data.microsoft.com', 1, 'sly9zk')
(0, 'v10.vortex-win.data.microsoft.com', 1, 'sly9zk')
(0, 'v20.events.data.microsoft.com', 1, 'sly9zk')
(0, 'v20.vortex-win.data.microsoft.com', 1, 'sly9zk')
(0, 'valid.apple.com', 1, 'Security certificate validation. - sly9zk')
(0, 'vcs.vdspf.com', 1, 'sly9zk')
(0, 'video-stats.l.google.com', 1, 'sly9zk')
(0, 'videos.vidible.tv', 1, 'sly9zk')
(0, 'vimeo.com', 1, 'sly9zk')
(0, 'vpp.itunes.apple.com', 1, 'MDM servers to perform operations related to Apps and Books, like assigning or revoking licenses on a device. - sly9zk')
(0, 'watson.telemetry.microsoft.com', 1, 'sly9zk')
(0, 'web.vortex.data.microsoft.com', 1, 'sly9zk')
(0, 'weblb-wg.dual-gslb.spotify.com', 1, 'sly9zk')
(0, 'widget-cdn.rpxnow.com', 1, 'sly9zk')
(0, 'wikipedia.org', 1, 'sly9zk')
(0, 'win10.ipv6.microsoft.com', 1, 'sly9zk')
(0, 'win1710.ipv6.microsoft.com', 1, 'sly9zk')
(0, 'winhelp2002.mvps.org', 1, 'sly9zk')
(0, 'wordpress.com', 1, 'sly9zk')
(0, 'wp.com', 1, 'sly9zk')
(0, 'ws-ee-maidsvc.icloud.com', 1, 'Schoolwork Roster service. - sly9zk')
(0, 'ws.audioscrobbler.com', 1, 'sly9zk')
(0, 'www.adf.ly', 1, 'sly9zk')
(0, 'www.aliexpress.com', 1, 'sly9zk')
(0, 'www.bit.ly', 1, 'sly9zk')
(0, 'www.dataplicity.com', 1, 'sly9zk')
(0, 'www.ecdinterface.philips.com', 1, 'sly9zk')
(0, 'www.google-analytics.com', 1, 'sly9zk')
(0, 'www.googleapis.com', 1, 'sly9zk')
(0, 'www.howtogeek.com', 1, 'sly9zk')
(0, 'www.itunes.com', 1, 'sly9zk')
(0, 'www.linuxtracker.org', 1, 'sly9zk')
(0, 'www.msftncsi.com', 1, 'sly9zk')
(0, 'www.no-ip.com', 1, 'sly9zk')
(0, 'www.opensubtitles.org', 1, 'sly9zk')
(0, 'www.ow.ly', 1, 'sly9zk')
(0, 'www.plex.tv', 1, 'sly9zk')
(0, 'www.propublica.org', 1, 'sly9zk')
(0, 'www.refersion.com', 1, 'sly9zk')
(0, 'www.samsungotn.net', 1, 'sly9zk')
(0, 'www.solaredge.com', 1, 'sly9zk')
(0, 'www.squaretrade.com', 1, 'sly9zk')
(0, 'www.twitter.com', 1, 'sly9zk')
(0, 'www.xboxlive.com', 1, 'sly9zk')
(0, 'www.youtube-nocookie.com', 1, 'sly9zk')
(0, 'xbox.ipv6.microsoft.com', 1, 'sly9zk')
(0, 'xboxexperiencesprod.experimentation.xboxlive.com', 1, 'sly9zk')
(0, 'xflight.xboxlive.com', 1, 'sly9zk')
(0, 'xkms.xbolive.com', 1, 'sly9zk')
(0, 'xp.apple.com', 1, 'sly9zk')
(0, 'xsts.auth.xboxlive.com', 1, 'sly9zk')
(0, 'yahoo.com', 1, 'sly9zk')
(0, 'youtu.be', 1, 'sly9zk')
(0, 'youtube-nocookie.com', 1, 'sly9zk')
(0, 'youtube.com', 1, 'sly9zk')
(0, 'yt3.ggpht.com', 1, 'sly9zk')
(0, 'z.cdn.turner.com', 1, 'sly9zk')
(0, 'zeustracker.abuse.ch', 1, 'sly9zk')
