(0, 'albert.apple.com', 1, 'Device activation. - sly9zk')
(0, 'appldnld.apple.com', 1, 'iOS updates. - sly9zk')
(0, 'appleid.apple.com', 1, 'sly9zk')
(0, 'ax.phobos.apple.com.edgesuite.net', 1, 'sly9zk')
(0, 'captive.apple.com', 1, 'Internet connectivity validation for networks that use captive portals. - sly9zk')
(0, 'cf.iadsdk.apple.com', 1, 'sly9zk')
(0, 'configuration.apple.com', 1, 'Rosetta 2 updates. - sly9zk')
(0, 'crl.apple.com', 1, 'Security certificate validation. - sly9zk')
(0, 'crl.entrust.net', 1, 'Security certificate validation. - sly9zk')
(0, 'crl3.digicert.com', 1, 'Security certificate validation. - sly9zk')
(0, 'crl4.digicert.com', 1, 'Security certificate validation. - sly9zk')
(0, 'deviceenrollment.apple.com', 1, 'DEP provisional enrollment. - sly9zk')
(0, 'deviceservices-external.apple.com', 1, 'sly9zk')
(0, 'diagassets.apple.com', 1, 'Used by Apple devices to help detect possible hardware issues. - sly9zk')
(0, 'gdmf.apple.com', 1, 'Used by an MDM server to identify which software updates are available to devices that use managed software updates. - sly9zk')
(0, 'gg.apple.com', 1, 'iOS, tvOS, and macOS updates. - sly9zk')
(0, 'gnf-mdn.apple.com', 1, 'macOS updates. - sly9zk')
(0, 'gnf-mr.apple.com', 1, 'macOS updates. - sly9zk')
(0, 'gs.apple.com', 1, 'macOS updates. - sly9zk')
(0, 'humb.apple.com', 1, 'sly9zk')
(0, 'iadsdk.apple.com', 1, 'sly9zk')
(0, 'identity.apple.com', 1, 'APNs certificate request portal. - sly9zk')
(0, 'ig.apple.com', 1, 'macOS updates. - sly9zk')
(0, 'iprofiles.apple.com', 1, 'Hosts enrollment profiles used when devices enroll in Apple School Manager or Apple Business Manager through Device Enrollment. - sly9zk')
(0, 'isu.apple.com', 1, 'sly9zk')
(0, 'itunes-apple.com.akadns.net', 1, 'sly9zk')
(0, 'itunes.apple.com', 1, 'App Store - sly9zk')
(0, 'itunes.apple.com.edgesuite.net', 1, 'sly9zk')
(0, 'itunes.com', 1, 'sly9zk')
(0, 'lcdn-registration.apple.com', 1, 'sly9zk')
(0, 'mdmenrollment.apple.com', 1, 'MDM servers to upload enrollment profiles used by clients enrolling through Device Enrollment in Apple School Manager or Apple Business Manager, and to look up devices and accounts. - sly9zk')
(0, 'mesu.apple.com', 1, 'Hosts software update catalogs. - sly9zk')
(0, 'news.iadsdk.apple.com', 1, 'sly9zk')
(0, 'ns.itunes.apple.com', 1, 'sly9zk')
(0, 'ocsp.apple.com', 1, 'sly9zk')
(0, 'ocsp.apple.com', 1, 'Security certificate validation. - sly9zk')
(0, 'ocsp.digicert.com', 1, 'Security certificate validation. - sly9zk')
(0, 'ocsp.entrust.net', 1, 'Security certificate validation. - sly9zk')
(0, 'ocsp.verisign.net', 1, 'Security certificate validation. - sly9zk')
(0, 'oscdn.apple.com', 1, 'macOS Recovery - sly9zk')
(0, 'osrecovery.apple.com', 1, 'macOS Recovery - sly9zk')
(0, 'ppq.apple.com', 1, 'Enterprise App validation - sly9zk')
(0, 'radarsubmissions.apple.com', 1, 'sly9zk')
(0, 'serverstatus.apple.com', 1, 'Content caching client public IP determination - sly9zk')
(0, 'setup.icloud.com', 1, 'Required to log in with a Managed Apple ID on Shared iPad. - sly9zk')
(0, 'skl.apple.com', 1, 'macOS updates. - sly9zk')
(0, 'sq-device.apple.com', 1, 'eSIM activation - sly9zk')
(0, 'static.ips.apple.com', 1, 'sly9zk')
(0, 'swcdn.apple.com', 1, 'macOS updates. - sly9zk')
(0, 'swdist.apple.com', 1, 'macOS updates. - sly9zk')
(0, 'swdownload.apple.com', 1, 'macOS updates. - sly9zk')
(0, 'swpost.apple.com', 1, 'macOS updates. - sly9zk')
(0, 'swscan.apple.com', 1, 'macOS updates. - sly9zk')
(0, 'tbsc.apple.com', 1, 'sly9zk')
(0, 'time-ios.apple.com', 1, 'Used by devices to set their date and time. - sly9zk')
(0, 'time-macos.apple.com', 1, 'Used by devices to set their date and time. - sly9zk')
(0, 'time.apple.com', 1, 'Used by devices to set their date and time. - sly9zk')
(0, 'updates-http.cdn-apple.com', 1, 'sly9zk')
(0, 'updates.cdn-apple.com', 1, 'sly9zk')
(0, 'valid.apple.com', 1, 'Security certificate validation. - sly9zk')
(0, 'vpp.itunes.apple.com', 1, 'MDM servers to perform operations related to Apps and Books, like assigning or revoking licenses on a device. - sly9zk')
(0, 'ws-ee-maidsvc.icloud.com', 1, 'Schoolwork Roster service. - sly9zk')
(0, 'www.itunes.com', 1, 'sly9zk')
(0, 'xp.apple.com', 1, 'sly9zk')
